### ISSUE TITLE
Text Label for screen/display is vulnerable to injection.

### ISSUE THREAD

**Issue by PMQABen** [ProcessMaker/processmaker#1356]
1. Go to `/processes/screens`
2. Create a new "DISPLAY" screen
3. Add a text control to the form
4. Place `<img src=x onerror=alert(123) />` in the "Text Label" field

**Result:**
![image](https://user-images.githubusercontent.com/28575916/52672569-16fa7280-2ed3-11e9-8d8c-19f37dd51e73.png)

**Note:**
Same thing occurs with the "Text Box" control for Screen/Form, when filling out the "text content" section.

**Comment by danloa** [comment]
@PMQABen  in the current version of Spark, any HTML tag es cleaned before saving it in the database. So that the alert you reported is displayed while designing the screen but when you reload the screen the issue doesn't happen again. So the code injection problem never happens. What do you think?

**Comment by PMQABen** [comment]
I'll follow-up with Alan to confirm, but last I read he didn't want HTML to be stripped from the Text Controls.
