### ISSUE TITLE
Session Timeout

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#1524]
- [x] Session background refresh
- [x] For components that emit messages, we need to add a listener that automatically resets the session
- [x] If a user is working in multiple tabs, all tabs must share the same session count down. 
- [x] Modal should show when a session is 95% expired
- [x] Modal progress bar should be dynamic with the session time
![Screen Shot 2019-04-09 at 4 12 25 PM](https://user-images.githubusercontent.com/29641725/55840983-48ae4500-5ae2-11e9-8076-717776943bf0.png)

**Comment by velkymx** [comment]
@ryancooley I added a screenshot

**Comment by velkymx** [comment]
I'm getting the window as I'm being timed out.

**Comment by velkymx** [comment]
This is still not behaving correctly. It shows the window AS the timeout is happening, then immediately redirects the user. It should allow them to make a choice or signing back in or refreshing their session, but now it shows then redirects to the login.

**Comment by velkymx** [comment]
This feature doesn't work at all :'(

**Comment by PMQABen** [comment]
* Sessions do not reset if the user is in the process modeler or screen builder.
* In Firefox, the session timeout modal does not appear at all.
* When a session timeout is set at 5 minutes, the warning modal appears with around 2min 55 seconds remaining. I don't think that's 95% expired.

**Comment by PMQABen** [comment]
No new code has been committed. At **_minimum_**, we at least need to fix the Firefox session modal not displaying before it can pass QA.

**Comment by PMQABen** [comment]
Turns out this was because Firefox refused to load socket.io, even though it gladly accepted the self-signed SSL cert for the local VM. :|
Good to go.
