### ISSUE TITLE
PM4 Import Test

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#1613]
We want a PM4 import that will test as much of the project as possible.

- Lua Support
- PHP Support
- User Assignment
- User Reassignment
- Group Assignment
- Hidden Values
- Computed Values
- Multi-Page Forms
- Exclusive Gateways
- Record List
- Time Events (nice to have TBD)

**Comment by velkymx** [comment]
@PMQABen where are we with this?

**Comment by PMQABen** [comment]
This is what I have so far. For some reason the "intermediate timer event" has now changed to an "intermediate message catch event", and trying to swap to an intermediate timer doesn't work (it can't connect to anything)
[qa_test-start_event.spark.txt](https://github.com/ProcessMaker/spark/files/3074461/qa_test-start_event.spark.txt) _(take off the .txt extension to make it work)_
![image](https://user-images.githubusercontent.com/28575916/56055164-b25e6700-5d0d-11e9-8672-984e34fc5833.png)

Any help y'all can give with filling in the gaps would be appreciated. The process should be able to be modified to handle User/Group assignment/reassignment, but the following I'm not sure how to make them work in the Process:
* Hidden Values
* Computed Values
* Record List

**Comment by velkymx** [comment]
This has been implemented by QA
