### ISSUE TITLE
Allow register of new Screen Builder components by packages

### ISSUE THREAD

**Issue by danloa** [ProcessMaker/processmaker#1658]
For a package to be able to add new componentes to the screen builder toolbox, we need to register some kind of configuration file,

**Comment by tdondich** [comment]
I'm confused, this already can be done.  Follow the same pattern as adding components to the modeler.  The screen builder already has a manager.  https://github.com/ProcessMaker/spark/blob/develop/ProcessMaker/Managers/ScreenBuilderManager.php

**Comment by danloa** [comment]
Already merged https://github.com/ProcessMaker/processmaker/pull/1664
