### ISSUE TITLE
Blank Start Event Changes to Timer Start

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#1712]
I created this basic flow, when I went back into the modeler the start event had changed to a timer start event.

![Screenshot 2019-04-22 09 51 45](https://user-images.githubusercontent.com/535300/56512451-41c10280-64e4-11e9-806f-4ad71da4feec.png)

**Comment by caleeli** [comment]
This was fixed with the last version of modeler moddle and spark in PR #1662, also take in count to rebuild the client (npm install;  npm run dev) to test it.
