### ISSUE TITLE
Validate Data Name

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#1746]
In the screen builder, we need to validate that the Field Name is a correctly formatted string we can use (lowercase, no spaces, etc, etc)

Rules for variables:

A variable name must start with a letter or the underscore character
A variable name cannot start with a number
A variable name can only contain alpha-numeric characters and underscores (A-z, 0-9, and _ )

**Comment by danloa** [comment]
> @danloa This is not working in develop

@velkymx  I can't reproduce the problem. I tested again with the following strings, all of them were correctly validated:
NormalName -> validated as OK
normalName  ->  validated as OK
_normalName  ->  validated as OK
_normal5Name  ->  validated as OK
_normalName123  ->  validated as OK
1wrong  ->  validated as error
1_wrong  ->  validated as error
wrong^name  ->  validated as error
wrong()name  ->  validated as error
wrong*name  ->  validated as error
wrong/name  ->  validated as error
wrong name  ->  validated as error
