### ISSUE TITLE
Populating Dropdowns via API

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#1795]
All dropdowns should have the following features:

1. Vue Multi-Select control - used for filtering and optionally multiple selections
2. A default value of "Select" 
2. If the select come from the API and there are no results, an error message should be shown

ex; Select a Display Screen
None Found
error: No Display Screens Found

**Comment by milaendo** [comment]
this ticket could potentially lead to validation problems just wanted to make sure this ticket was referenced: https://github.com/ProcessMaker/spark/issues/1740

**Comment by velkymx** [comment]
This has been implemented
