### ISSUE TITLE
Update build to include polyfills for supported browsers

### ISSUE THREAD

**Issue by ssshake** [ProcessMaker/processmaker#1842]
![image](https://user-images.githubusercontent.com/1675868/57895367-42199880-7819-11e9-992e-e35715ffe7b9.png)

- [x] Get a definitive list of minimum supported browser versions
- [x] Determine if its wise to polyfill everything or if we have to do it feature by feature
- [ ] Implement that in build step

Do we have to do this for every project? Yes

**Comment by ssshake** [comment]
@chipit24 for visibility

**Comment by velkymx** [comment]
Minimum Resolution 1200 x 720 pixels
Web Browsers (latest versions only)

Firefox
Chrome
Safari 
Edge

**Comment by tdondich** [comment]
We have saucelabs that we can use for cross browser automated tests.

**Comment by chipit24** [comment]
This is relevant for the standalone Vue apps as well. [`@babel/polyfill`](https://babeljs.io/docs/en/babel-polyfill) should handle polyfills for us automatically.
