### ISSUE TITLE
Avatar Upload Broken

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#1850]
Both uploading and saving aren't working correctly.

![Screenshot 2019-05-17 09 53 56](https://user-images.githubusercontent.com/535300/57943744-b2f89900-7889-11e9-88d0-3c8d877e123a.png)

**Comment by velkymx** [comment]
@danloa it's broken again. 

![image](https://user-images.githubusercontent.com/535300/59515162-529e4c80-8e73-11e9-90cc-8452bc0273ae.png)

**Comment by danloa** [comment]
Solved with the already merged PR
 https://github.com/ProcessMaker/processmaker/pull/2003
