### ISSUE TITLE
Script Timeout Test Failing

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#1869]
1) Tests\Feature\Api\TimeoutsTest::testLuaScriptTimeoutExceeded
Failed asserting that the log is empty.
Failed asserting that 1 matches expected 0.

/home/vagrant/processmaker/tests/Feature/Shared/LoggingHelper.php:62
/home/vagrant/processmaker/tests/Feature/Docker/TimeoutsTest.php:52
/home/vagrant/processmaker/tests/Feature/Docker/TimeoutsTest.php:119

2) Tests\Feature\Api\TimeoutsTest::testPhpScriptTimeoutExceeded
Failed asserting that the log is empty.
Failed asserting that 1 matches expected 0.

/home/vagrant/processmaker/tests/Feature/Shared/LoggingHelper.php:62
/home/vagrant/processmaker/tests/Feature/Docker/TimeoutsTest.php:52
/home/vagrant/processmaker/tests/Feature/Docker/TimeoutsTest.php:149

**Comment by marcoAntonioNina** [comment]
It is working in the current develop branch

**Comment by ryancooley** [comment]
Confirmed it is working. @velkymx we are unable to reproduce.

**Comment by danloa** [comment]
Tests are working in develop and locally:
https://github.com/ProcessMaker/processmaker/tree/bugfix/1869
