### ISSUE TITLE
Save Search Icons Missing Text

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#1904]
There's all this empty space next to the icons, like there's supposed to be a text description, but nothing exists. FIX: change this from a drop down to a 4x4 grid of icons with radio buttons to select

![image](https://user-images.githubusercontent.com/535300/58642189-a88ac600-82b1-11e9-9238-ad92d9173c89.png)

**Comment by nolanpro** [comment]
@velkymx is it OK if we just show the icon in a narrower dropdown? The translators were getting confused with text like "Fire Alt" and "Search Plus". Or should we come up with more intuitive names and keep the text labels?

**Comment by velkymx** [comment]
@nolanpro let's change this from a drop down to a 4x4 grid of icons with radio buttons to select.

**Comment by nolanpro** [comment]
Fixed in https://github.com/ProcessMaker/spark-package-savedsearch/commit/4caee8f7d14e17ffe8e73b68c6909b38530fcbd5

**Comment by nolanpro** [comment]
Closing since this was done in the above mentioned commit in saved search package
