### ISSUE TITLE
Collection: PMQL and Variables

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#1928]
I want to be able pass in a variable {{name}} into the PMQL in the collections inspector in screen builder.

**Comment by tdondich** [comment]
Note, if this is used, the control needs to watch the data to ensure that the "name" variable change makes the control re-execute the query.

If the control is re-executing the query, then the control should be disabled while loading takes place.

**Comment by tdondich** [comment]
Also, @velkymx , should this be filed in the collections project?

**Comment by velkymx** [comment]
@tdondich I don't think so. This will impact any of the PMQL powered form elements, not just collections.
