### ISSUE TITLE
File Upload Broken

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#1963]
When using the file upload functionality it fails with an error about the filename. Whatever the underlying issue is, we need to get this fixed.

**Comment by velkymx** [comment]
So it seems to copy the filename to the variable name without the prefix. But if the variable name contains dots or numbers, it’ll be passed through vue-deepset and interpreted as a deep model path

**Comment by caleeli** [comment]
Could we have a Definition of how this control should work? What do you mean by prefix?

I configured the control this way:
![image](https://user-images.githubusercontent.com/8028650/59361246-88babf80-8cff-11e9-9d4e-75865928faae.png)

Then when I run the process and uploaded a file, I get the following result:

![image](https://user-images.githubusercontent.com/8028650/59361341-b56ed700-8cff-11e9-8ded-a0acaa0c403d.png)

I can see that there is a data that should not be there: **"filesUploaded.property": null**
