### ISSUE TITLE
Create vs Edit Permissions

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2030]
In BETA 6 - when you add a permission, if you add the CREATE permission in any category, it automatically adds EDIT. But then if you click on EDIT, it removes both. And then if you click EDIT again, it will now add only EDIT without CREATE. Is this intentional behavior?

Should allow: 

Create Permissions with Edit
but also
Edit without Create

**Comment by caleeli** [comment]
Look it is working like that. It allows:

- Create + Edit
- Edit without Create

and disallows:

- Create without Edit

![image](https://user-images.githubusercontent.com/8028650/60022113-3368a180-9661-11e9-8f9f-a30d60724e25.png)
![image](https://user-images.githubusercontent.com/8028650/60022134-3b284600-9661-11e9-8bc8-d2ba61fab248.png)
