### ISSUE TITLE
User Avatar Upload Fails

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2069]
The API timed out, but i was able to save it after retrying. I'll have a deeper look. Other users are reporting it is broken. Confirm it works on both routes:

- [x] /profile/edit
- [x] /admin/users/1/edit

**Comment by marcoAntonioNina** [comment]
work properly.

**Comment by nolanpro** [comment]
Also confirmed working
- admin can change their avatar
- admin can change other user's avatar
- regular user can change their own avatar
- regular user with permission to edit users can change other user's avatars
