### ISSUE TITLE
User Local Time Wrong

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2088]
The local time in the profile should show the time in the timezone set for that user. In this case below the time locally is 14:20 and in La Paz it is 17:20

![image](https://user-images.githubusercontent.com/535300/60843537-c9d1b280-a18b-11e9-8c9e-01b259ab5342.png)

![image](https://user-images.githubusercontent.com/535300/60843545-d35b1a80-a18b-11e9-8ad0-b6c756257b79.png)

**Comment by danloa** [comment]
@velkymx  I can't reproduce the problem. Can you share the .env file to see the timezone configuration that generated the error?

**Comment by danloa** [comment]
It works in develop and locally. For example this is the time displayed when using America/La_Paz (-4):

![image](https://user-images.githubusercontent.com/14875032/62627702-e9c5d480-b8f7-11e9-8471-6d7448d75b98.png)

And changed immediately to UTC, all times are displayed correctly (+0)

![image](https://user-images.githubusercontent.com/14875032/62627747-fcd8a480-b8f7-11e9-8a94-b4871dba6d4f.png)

**Comment by velkymx** [comment]
Great.
