### ISSUE TITLE
Auth Token Requires Email for Username

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2097]
When using the grant token feature, I am forced to use the user's email as the username instead of the username. Should use the username.

![image](https://user-images.githubusercontent.com/535300/60979924-5f825480-a2e8-11e9-87d5-3c069904f526.png)

**Comment by nolanpro** [comment]
Closing since this was done in another commit https://github.com/ProcessMaker/processmaker/commit/ab7396ac1e778c065df8b98faa7d3f6d0197a5a4#diff-9105469c422019fe22387bc5a6884fadR318
