### ISSUE TITLE
ID and Variable Name Configuration in Image Control Element Need to be Removed

### ISSUE THREAD

**Issue by Aaron-Cushman** [ProcessMaker/processmaker#2098]
The Image Control in ProcessMaker has an ID name and a Variable Name in the configuration that don't get used at all when using it. You can enter text into the ID Field and the Variable Name field. However, when trying to reference the variable name on another page or another screen, the image doesn't show up. 
![Screen Shot 2019-07-10 at 9 01 53 AM](https://user-images.githubusercontent.com/52578982/60985265-091a1380-a2f2-11e9-9c8a-5617d3711749.png)

**Comment by velkymx** [comment]
This is implemented
