### ISSUE TITLE
System Permissons

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2100]
The file system is failing to accept uploads if the permissions are incorrectly set. Add a unit test to confirm that the permissions are correct and you are able to upload files and the user avatar.

**Comment by nolanpro** [comment]
@velkymx Looks like david added a pretty comprerensive test as part of his PR https://github.com/ProcessMaker/processmaker/pull/2123/commits/bef337b2d56d2082390f9208e76003d0e185ce1f
