### ISSUE TITLE
API Tokens Returns Same ALWAYS

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2128]
Doesn't matter the user, I get the same list of tokens from the API.

UI: /admin/users/1/edit

API: /api/1.0/users/1/tokens

**Comment by velkymx** [comment]
![image](https://user-images.githubusercontent.com/535300/61242015-87fbbb80-a6f9-11e9-81ff-155bf65752fa.png)

![image](https://user-images.githubusercontent.com/535300/61242028-94801400-a6f9-11e9-8692-4d7330386988.png)

**Comment by velkymx** [comment]
@danloa can you add some unit tests to this feature?

**Comment by danloa** [comment]
Already merged
