### ISSUE TITLE
CircleCI phpunit step is silently failing

### ISSUE THREAD

**Issue by nolanpro** [ProcessMaker/processmaker#2140]
CI continues and shows green even when there are failing tests:

ex: https://circleci.com/gh/ProcessMaker/processmaker/8162

![image](https://user-images.githubusercontent.com/2546850/61404562-8a424f00-a88c-11e9-8ec8-08bdb37c1937.png)

**Comment by velkymx** [comment]
https://processmaker.atlassian.net/browse/SCO-3595
