### ISSUE TITLE
Need better installation instructions

### ISSUE THREAD

**Issue by Pip3queak** [ProcessMaker/processmaker#2152]
Is there a comprehensive installation manual for PM4? I have tried following the instructions on the github page using a new CentOS environment, but I'm confused by “npm install”, “composer install” - in the end, I have to find other resources to install these. Even then, I get confused on how to properly set up the software and would really appreciate a more user-friendly guide.

**Comment by tdondich** [comment]
Hi @Pip3queak , thanks for being interested.

First off, you'll want to install from one of the releases on our github releases page. This will help you get started with a more formal beta release.  The README instructions are more for setting up developer environments if you plan on contributing/working on Processmaking 4.

We've just made the documentation available for installing one of those releases. You can find our user documentation (which is still very much under construction) at https://processmaker.gitbook.io/processmaker/

https://processmaker.gitbook.io/processmaker/install-processmaker/installation-guide

Note, in the installation guide, be sure to download the latest beta from our github releases page.

**Comment by tomolimo** [comment]
Hello @tdondich, 
Unfortunately, the URL you gave doesn't show any installation procedure for test purposes, it gives only instruction for development purposes....
Don't you have any installation procedure for testing?
Thank you
Regards,
Tomolimo

**Comment by Askylh** [comment]
Hello,
The problem is still here, there is no documentation to install PM4 in prod environment.

regards

**Comment by tomolimo** [comment]
Hello @tdondich 
How is it possible to do an evaluation of this great application if it's not possible to install it in an "easy" way having a clear guideline for that purpose?
Thank you,
Regards,
Tomolimo

**Comment by tdondich** [comment]
At this time, the installation for the open source is only intended for local testing/development purposes.  Right now, any production enivonments, we recommend you reaching out to us so we can provide a trial and potential production environment deployed in AWS.  We're hoping to get to some deployment instructions but at this time, it's lower priority.  If someone wants to contribute deployment instructions based off of the README (which describes all dependent services, etc), I'd love to see a PR!
