### ISSUE TITLE
Generate CSS override

### ISSUE THREAD

**Issue by danloa** [ProcessMaker/processmaker#2157]

**Comment by velkymx** [comment]
- [ ] Database scheme should be: ID (autoint), Name (unique in DB), Content (JSON), Date Created, Data Updated
- [ ] Setting Factory should include all values
- [ ] Font header : Custom Font
- [ ] NPM Error on install
- [ ] Compiler randomly disappears
- [ ] Logos aren't scaling properly to the set dimensions (150x40, 40x40)
