### ISSUE TITLE
New Translation: Event Gateway

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2186]
The text for "Event-Based Gateway" is untranslated. Investigate and confirm all modeler components translate correctly into all languages.

**Comment by PMQABen** [comment]
![image](https://user-images.githubusercontent.com/28575916/72185653-2ebecd00-33a8-11ea-84b8-60492e90c8b9.png)
Issue still occurs, reopening. :(

**Comment by PMQABen** [comment]
Fixed with latest translations.
