### ISSUE TITLE
Email Connector: Text Controls do not display.

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2187]
Description
Install the https://github.com/ProcessMaker/connector-send-email package
Create an Email-Type Form
Add a Table Control
Add one or more Text Controls inside the Table
Preview the form
Result:
Text Controls do not display.

**Comment by marcoAntonioNina** [comment]
It is solved with this pull request:

https://github.com/ProcessMaker/connector-send-email/pull/31

![textControl](https://user-images.githubusercontent.com/1747025/62139902-1191b880-b2b8-11e9-8b13-f5de05f7ff7d.gif)
