### ISSUE TITLE
SQL Column Missing

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2190]
![image](https://user-images.githubusercontent.com/535300/62066595-8f858f00-b1e6-11e9-8541-6fe433372d71.png)

**Comment by danloa** [comment]
@velkymx , The problem can't be replicated.  It seems that your database has and old version or may be this column was unintentionally dropped?. The column is created in the  file:

database/migrations/2018_09_07_180640_create_process_request_tokens.php

May be _php artisan migrate:fresh --seed_   solve the problem?

**Comment by velkymx** [comment]
> @velkymx , The problem can't be replicated. It seems that your database has and old version or may be this column was unintentionally dropped?. The column is created in the file:
> 
> database/migrations/2018_09_07_180640_create_process_request_tokens.php
> 
> May be _php artisan migrate:fresh --seed_ solve the problem?

Hmm... we could get the logs, but they're running a build from develop.

**Comment by velkymx** [comment]
@daniel-ryan-PM can you add the missing column?

**Comment by Kookster310** [comment]
I've added the column to the database:
`| element_index             | int(10) unsigned                                                        | NO   |     | 0       |                |
+---------------------------+-------------------------------------------------------------------------+------+-----+---------+----------------+`

**Comment by velkymx** [comment]
Thanks @Kookster310
