### ISSUE TITLE
Request Data Empty

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2191]
I tried to edit the data of a completed request and it returned a blank editor.

![image](https://user-images.githubusercontent.com/535300/62082133-059aed80-b209-11e9-9619-d6758a86ba58.png)

**Comment by sanjacornelius** [comment]
Data object returns empty when there is an error within the request and the request is manually completed.

**Comment by velkymx** [comment]
https://github.com/ProcessMaker/processmaker/issues/2229

**Comment by sanjacornelius** [comment]
Reopening this ticket, the ticket was prematurely closed.
