### ISSUE TITLE
New Install Script Failing

### ISSUE THREAD

**Issue by sanjacornelius** [ProcessMaker/processmaker#2235]
On a fresh install, the attach doc was the first error encountered, however, you are able to finish the installation even with that error. Below are the second errors outputted, which is causing issues with OAuth. Running `php artisan passport:install` was a fix for these errors.

Look into why the installer script isn't working properly.   

```[2019-08-05 22:07:46] production.ERROR: Key path "file:///opt/processmaker/storage/oauth-public.key" does not exist or is not readable {"exception":"[object] (LogicException(code: 0): Key path \"file:///opt/processmaker/storage/oauth-public.key\" does not exist or is not readable at /opt/processmaker/vendor/league/oauth2-server/src/CryptKey.php:48)```

on UI
[error_output.txt](https://github.com/ProcessMaker/processmaker/files/3469611/error_output.txt)

```
Sorry! API failed to load

Something went wrong. Try refreshing the application```

**Comment by nolanpro** [comment]
Todo: Need to test this on amazon install environment that @Kookster310 is using: https://hub.docker.com/_/amazonlinux:2
