### ISSUE TITLE
Schedule Tasks Column Missing

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2239]
![image](https://user-images.githubusercontent.com/535300/62577380-b0d42400-b853-11e9-8a2b-107d5d30be09.png)

**Comment by ryancooley** [comment]
This is due to a migration which was _updated_ instead of a _new migration created_. Can be solved on existing instances without data loss by running the following SQL:

```sql
ALTER TABLE `scheduled_tasks` ADD `process_request_token_id` INT  UNSIGNED  NULL  DEFAULT NULL  AFTER `process_request_id`;
ALTER TABLE `scheduled_tasks` ADD INDEX `scheduled_tasks_process_request_token_id_index` (`process_request_token_id`);
```

**Comment by Kookster310** [comment]
Column and index added to the table. Confirmed working in beta8-demo.

**Comment by ryancooley** [comment]
@velkymx Are there any other instances you're aware of that need to be updated or should we close this ticket?

**Comment by velkymx** [comment]
I think we're good.
