### ISSUE TITLE
Completed Task Sidebar Missing

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2263]
Route  /tasks/3/edit

![missing-sidebar](https://user-images.githubusercontent.com/535300/62884978-9df69f00-bcec-11e9-87c9-f69e6d1c3720.png)

**Comment by danloa** [comment]
@velkymx  the side bar isn't shown if the completed task is and Event. For some reason the End Events are listed in the completed requests list. Do this is correct?
![image](https://user-images.githubusercontent.com/14875032/62974121-8222f400-bde5-11e9-9521-83ec44591c0c.png)
