### ISSUE TITLE
Unauthorized API

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2322]
If an API endpoint is unauthorized, current behavior redirects to a login page. Instead it must return the status 401 (Unauthorized) with following JSON payload:

```
{
    "error": "Not Authorized"
}
```

**Comment by PMQABen** [comment]
On current "staging-pm4" branch:
```
{
  "error": "Unauthenticated."
}
```
Payload response needs to be "Not Authorized"

**Comment by sanjacornelius** [comment]
@velkymx I remember this PR was in regards to a specific test that was failing, however, I am not finding that test anymore. 

I do remember however that in the test `$this->get()` is was used which is a web call and doesn't set the right headers, which why the test is failing and being redirected to the login page. And that the `$this->json()` method needed to be used instead. This will set the correct headers for the API call and return 401.

**Comment by sanjacornelius** [comment]
@velkymx Should we close this ticket?

**Comment by velkymx** [comment]
Closing. thanks!
