### ISSUE TITLE
Package Installer Broken

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2323]
Steps to Reproduce:

Go to a new PM4 installation

Follow the instruction to install packages package

https://github.com/ProcessMaker/packages

Current Behavior:

The installation gives an error

![image](https://user-images.githubusercontent.com/535300/63796410-ddabb200-c8ba-11e9-94c0-5e0605c5d7e3.png)

**Comment by caleeli** [comment]
Nice @nolanpro, thanks, I am also testing the new steps in Readme, and it is working good.

**Comment by PMQABen** [comment]
This might be a related issue, when you first install PM4 and run "php artisan" you see:
```
 package
  package:discover                           Rebuild the cached package manifest
```

After you install the "Packages" package and you run "php artisan", you see:
```
 package
  package:discover                           Rebuild the cached package manifest
  package:install                            Installs a selected package
  package:uninstall                          Uninstalls a selected package
 packages
  packages:install                           Installs the required js files and table in DB
  packages:uninstall                         Uninstalls Package Skeleton
```

This seems very odd.
