### ISSUE TITLE
Form History Tab

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2369]
Forms review sections have icons for both 🔎 (Details) and 🖨 (Print). However when clicking on *Details*, the browser's Print feature also triggers, in addition to expanding the form.  The print action should ONLY be trigged if the print icon is explicitly clicked.

**Comment by PMQABen** [comment]
This isn't happening in the main develop branch.

**Comment by marcoAntonioNina** [comment]
The error cannot be reproduced in the develop branch.
