### ISSUE TITLE
Can I use this in production ?

### ISSUE THREAD

**Issue by hdshariati** [ProcessMaker/processmaker#2401]
I'm interesting in using your new product for my customer.
What would be risk as security if I do that?
How can I migrate colosa/processmaker to it?

**Comment by velkymx** [comment]
Hi @hdshariati you can definitely use this project in production. We're still working through our feature setup, so changes may occur. As for migration from older products, at this time, it is not supported.

**Comment by Heshmatkhah** [comment]
Hi,
Is there an instruction for deploying this version without Vagrant?
