### ISSUE TITLE
.env -> production

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2406]
When running the installer via CLI, the .env file should always set...

APP_NAME="ProcessMaker"
APP_ENV=production
APP_DEBUG=FALSE

**Comment by nolanpro** [comment]
@velkymx blocked on #2407 and need some input from @caleeli since I think this is related to multiple databases

**Comment by nolanpro** [comment]
@PMQABen can you confirm this as a non issue? thanks

**Comment by PMQABen** [comment]
**Need More Information: Cannot Reproduce**
It's always put those three lines into the .env file. I re-ran `art processmaker:install` and the .env file was created as expected with FALSE/"ProcessMaker"/production. Same thing happened after I completely reinstalled PM4.

Send this back to the original reporter for more detail.
