### ISSUE TITLE
Installer broken if db name is anything other than 'processmaker'

### ISSUE THREAD

**Issue by nolanpro** [ProcessMaker/processmaker#2407]
Heres what I get when specifying `processmaker2` as the db name. Using same for data (but the issue is still there if you use a different data database)
```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'processmaker2.migrations' doesn't exist (SQL: select `migration` from `migrations` order by `batch` asc, `migration` asc)
```
If you replace the migrate command with `exec('php artisan migrate:fresh --seed --force')` it works fine (but that seems very very wrong). Laravel does not have a way to reload the kernel.

**Comment by tdondich** [comment]
Call the config helper to set the new value directly into the running
config.  It should kick it into gear.
