### ISSUE TITLE
New Collection Select does not consistently trigger update emit on VueFormRenderer

### ISSUE THREAD

**Issue by ryancooley** [ProcessMaker/processmaker#2413]
Bug resolved in Processmaker/vue-form-elements#96. Will need to build vue-form-elements, screen-builder, modeler, etc and bring changes into core.

**Comment by danloa** [comment]
This issue will be solved in the form-elements project, issue https://github.com/ProcessMaker/vue-form-elements/issues/96

**Comment by ryancooley** [comment]
Closed in https://github.com/ProcessMaker/vue-form-elements/issues/96
