### ISSUE TITLE
Request Summary Permissions

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2438]
The permissions seem a little off in the request detail.

If a user is a participant, then they can view the request detail

If the user, set in the process config as data editor, then they should see the data tab

**Comment by tdondich** [comment]
No.  I think they should still be able to access it.  100%.  Worst case
scenario is we add a permission to see the summary tab.  But I think we
just leave it as they can see everything and get feedback after we deploy.
