### ISSUE TITLE
Vue Form Elements documentation

### ISSUE THREAD

**Issue by sanjacornelius** [ProcessMaker/processmaker#2450]
@velkymx  here is a link to the documentation.
https://processmaker.atlassian.net/wiki/spaces/PM4/pages/584319186/Vue+Form+Elements

**Comment by velkymx** [comment]
@sanjacornelius this is a great first pass. Next please update the docs with how to use each vue component. I'd like to see the bindings, models and output (emit) that each element has.

See these docs as an example: https://bootstrap-vue.js.org/docs/components/form-select
or the vue examples: https://vuejs.org/v2/guide/components.html

The primary goal is to understand HOW to use each element (not necessarily as part of the screen builder)

**Comment by velkymx** [comment]
For example: 
**FormInput**
_Renders an input field, allowing types of text, password, email, search, date, datetime-local_

**Field Parameters**
The following are parameters used in the components to configure it

v-model (required)
Provides two-way binding to a variable.

name (required)
Specify the name of the field. This is used for certain operations and for labeling when used with validation rules.

type (optional for input type)
Specifies the type for the input field. This can be text(default) or password or any other html5 supported type.

options (required for select and radio button group)
An array of objects that represents possible options for the field. Each object contains two properties. 'content' is the text label of the option. 'value' is the value that will be assigned if the option is selected.

error (optional)
An optional error to render with the field.

rows (optional, for textarea field)
The number of rows to provide input for the textarea control.

**Output**

Emits the following values on load
Emits the following on blur

etc, etc, etc
