### ISSUE TITLE
Script Task Not Redirecting Properly

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2455]
Starting a request with the script task as the first task doesn't automatically redirect you to the first form task.

**Comment by caleeli** [comment]
@velkymx That feature does not exists. Also what happens if the **first form task is assigned to a user different** to the one who started the request?

**Comment by velkymx** [comment]
@caleeli Here's the BPMN. Although I'm hearing that it seems to be working....

https://www.dropbox.com/s/xwuj0cy75acm9ma/leave_of_absence_process%20%288%29.json?dl=0

**Comment by velkymx** [comment]
There is a fixed deployed to develop.
