### ISSUE TITLE
Validations issues shows as server error

### ISSUE THREAD

**Issue by jemiris** [ProcessMaker/processmaker#2473]
Hi,
I have not filled some fields it shows as required as well as it shows as a server error

![validation error](https://user-images.githubusercontent.com/27679841/67259727-0617ed00-f4b5-11e9-930e-18d2b26b1d08.png)

**Comment by tdondich** [comment]
@velkymx Know if this is solved in GA?

**Comment by velkymx** [comment]
This is resolved in GA
