### ISSUE TITLE
While running a process issue with sockect io

### ISSUE THREAD

**Issue by jemiris** [ProcessMaker/processmaker#2479]
Hi,
While starting a new process console issue with socket io. Attached screen below
![case running](https://user-images.githubusercontent.com/27679841/67451785-fc21f580-f63e-11e9-8ddb-0debd7cf5c57.png)

**Comment by tdondich** [comment]
Hi @jemiris , the error messages in google console show that the host of jemiris.developer.beta.processmaker.com isn't found. Make sure your broadcaster host configuration in your .env file is set to your socket.io server appropriately.
