### ISSUE TITLE
Packagize Modeler

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2491]
Convert the integrated modeler into a package. Include all of the configuration happening in PM4Core and move to the package.

Steps to develop and test:
1. Follow instructions on package development in the readme https://github.com/ProcessMaker/processmaker/blob/feature/2491/README.md#developing-packages
1. Checkout branch feature/2491 in core
1. Checkout branch feature/convert-to-package in modeler
1. In Core, add to composer.json repositories
    ```
    {
      "type": "path",
      "url": "path to modeler repo with branch feature/convert-to-package checked out"
    }
    ```
1. In Core (in vagrant), run `composer require processmaker/package-modeler`
1. In Modeler Repo, run `npm run mix`
1. In Core (in vagrant), run `php artisan package-modeler:install` to publish asses created by mix

Any time you change code in modeler run `npm run mix` in modeler and `php artisan package-modeler:install` in core (in vagrant)

Remaining Todo:
- [ ] Fix `TypeError: dia.Graph: cell type must be a string`
- [ ] Elements not rendering on graph/paper when dropped or loaded from xml. Xml appears to be correct. This looks like it might be different instances of the global vue object conflicting but i'm not sure.
- [x] Fix location of svg images, probably a setting webpack.mix.js

**Comment by nolanpro** [comment]
Steps to test:

1. In Core, add to composer.json repositories
    ```
    {
      "type": "path",
      "url": "path to modeler repo with branch feature/convert-to-package checked out"
    }
    ```
1. In Modeler Repo, run `npm run mix`
1. In Core, run `composer require processmaker/package-modeler` and `php artisan package-modeler:install`

Any time you change code in modeler run `npm run mix` in modeler and `php artisan package-modeler:install` in core
