### ISSUE TITLE
New Process Modal Not Resetting

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2512]
**Steps**

1. Go to Designer > Processes
2. Click "+ Process"
3. Close the modal by pressing the X
4. Click "+ Process" again, notice the modal fields are empty
5. Fill out all the fields, but click outside of the modal to close it, instead using do not use the X
6. Click "+ Process" one last time

**Current Behavior**

The modal fields are not cleared when the modal is not closed by clicking the X

**Expected Behavior**

The fields should be cleared regardless of what method the modal is closed

**Comment by nolanpro** [comment]
It's using the raw bootstrap model. Needs to be converted to bootstrap-vue. Will do as part of this issue

**Comment by sanjacornelius** [comment]
Closing. Issue is solved in PR #2590
