### ISSUE TITLE
New Category Modal Not Resetting

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2513]
1. Go to Designer > Category (these steps can be followed in Processes/Archived Processes/Scripts/Screens)
4. Click +Category, notice the modal fields are empty
6. Close the modal by pressing the X
8. Click +Category again, notice the modal fields are empty
10. Fill out all the fields, but click outside of the modal to close it, do not use the X
12. Click +Category one last time

**Current Behavior**
The modal fields are not cleared when the modal is not closed by clicking the X

**Expected Behavior**
The fields should be cleared regardless of what method the modal is closed

**Comment by sanjacornelius** [comment]
PR has been merged.
