### ISSUE TITLE
Yo Soy Espanol

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2533]
Make sure all references to this copy in the front end is removed and a proper translation is used instead.

**Comment by velkymx** [comment]
Also review the console log and make sure all "Translation Missing" strings are added

**Comment by sanjacornelius** [comment]
Closing. This issue is solved with the [package-actions-by-email PR #24 ](https://github.com/ProcessMaker/package-actions-by-email/pull/24)
