### ISSUE TITLE
Category Selects Pagination

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2536]
When loading the categories into the select boxes for new items (screens, scripts, etc) the API is paginating the results. It should show them all.

**Comment by velkymx** [comment]
See FOUR-734

**Comment by caleeli** [comment]
The categories control has a text search option to find the ones that are in later pages.

![categories](https://user-images.githubusercontent.com/8028650/71185491-e8b39500-2251-11ea-8bb3-ac1128ce00d6.gif)

**Comment by danloa** [comment]
https://processmaker.atlassian.net/browse/FOUR-734
