### ISSUE TITLE
Filter Categories for Screens and Scripts

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2574]
Category search/filtering doesn’t seem to work on screens or scripts. 

Does appear to work on processes.

**Comment by PMQABen** [comment]
This was reported in September in JIRA as https://processmaker.atlassian.net/browse/FOUR-711 but I closed it on Friday. Searching for scripts/screens does not equal searching for categories.

Bad QA, no cookie. :|

**Comment by PMQABen** [comment]
It's still not searching by wildcard.
