### ISSUE TITLE
Advanced Forms

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2595]
**User Story**

Use goes to the screen’s area of the application and selects the screen type “Form (Advanced)” and then enters the editor. Instead of the Vue screen builder they are presented with a Monaco editor with a basic HTML template preset up. The template has presetup the html tags, bootstrap and a global javascript object with basic variables available. The user then proceeds to design their own HTML/Javascript form for inclusion in their process. 

**Use Case**
Designer setups up a custom Advanced Form using their own HTML/Javascript. The request is run and the Advanced form is loaded in an iFrame on the task detail page. The parent window listens for the task to be completed. Upon the task moving to completed/closed status, the page redirects to the user's todo list.

**At Design Time**
- [x] Add new screen type to the database "Form (Advanced)"
- [x] Add a new blade using Monaco that loads the form data into the editor
- [x] Save HTML in the config column
- [x] New screens to use the below template
- [x] Include AXIOS sample using variables + CDN

**At Run Time**
- [x] New blade that has an iframe instead of the form (keep existing sidebar)
- [x] Pass in token necessary to complete the task via the API - [@nolanpro]
- [x] On Task completion capture the task complete event and redirect

**Demo Sample**
- [x] Create robust example in sample code [@ryancooley]
- [ ] Create demo version we can show off

**Default Template**
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Bare - Start Bootstrap Template</title>
  <!--Do Not Delete Below -->
 <link href="LINKTOOURBOOTSTRAPCSS" rel="stylesheet">
<script type =”javascript”>
Global Javascript object with VARIABLES HERE
</script>
  <!--Do Not Delete Above -->
</head>
<body>
<!-- 
Basic usage sample using Axios and a CDN
-->
</body>
</html>
```

**Default Variables**

url - the url of the end point to save the form
token - for authenticating to the end point - same as used in a current form 
data - this i the request variables and _request magic variables

**Comment by ryancooley** [comment]
Just want to note that when we continue implementing this we should ensure that Advanced Form types can be chosen for use in Collections as well.

**Comment by nolanpro** [comment]
... and web entry
