### ISSUE TITLE
Data Sources Changes

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2624]
Change icon to the cog

**Comment by velkymx** [comment]
![image](https://user-images.githubusercontent.com/535300/69985728-ab7ca280-14f0-11ea-851f-69b291520c2f.png)

**Comment by velkymx** [comment]
![image](https://user-images.githubusercontent.com/535300/69985754-b3d4dd80-14f0-11ea-92d8-3e1a4cce323f.png)

**Comment by velkymx** [comment]
Change name of BPMN element to Data Connector

**Comment by marcoAntonioNina** [comment]
review https://github.com/ProcessMaker/package-data-sources/pull/32
