### ISSUE TITLE
Data Object Missing from Select Lists

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2633]
When using a Select List in the screen builder there is no way to use an existing array. Instead you are presented with the Data Connector config. 

Fix:
Keep the current config for data object, but rename it to be Data Connector.

Return the Data Object as defined as the use of an existing array generate via the request.

**Comment by danloa** [comment]
This ticket is resolved in the screen builder project. Needs the following branch to be tested:

https://github.com/ProcessMaker/screen-builder/tree/bugfix/455
