### ISSUE TITLE
Select List Radio/Checkbox Spacing

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2635]
There needs to be spacing between the form checkbox/radio and the text. Right now they touch.

![image](https://user-images.githubusercontent.com/535300/70171149-faf2d800-1682-11ea-9afc-9d8fbbdd55e0.png)

![image](https://user-images.githubusercontent.com/535300/70171161-0219e600-1683-11ea-8cf6-0af60e6d509f.png)

**Comment by marcoAntonioNina** [comment]
need https://github.com/ProcessMaker/vue-form-elements/pull/128
