### ISSUE TITLE
Screen Builder: "watching" variable does not update to match a change in the screen

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2637]
Description

1. Create/Edit a Screen
1. Add any input control to the screen, call it "foo"
1. Create a Watcher for the input control
1. Rename the input control to "foobar"
1. Open the Watchers panel & notice the text under the "Watching" column

Result:

The column still shows "foo", even though the input has been changed to "foobar". Saving and reloading the page does not update the Watcher config.

**Comment by caleeli** [comment]
@velkymx  The Watcher is associated to a "Variable name" not to a "Control", so if the control changes its "Variable name" it will not change the variable name in any other places like Watcher (other examples could be calculated fields and grid columns)

**Comment by velkymx** [comment]
We need a more comprehensive fix for this. Changing the variable name in the Inspector config, needs to update all references to that variable in all situations.
