### ISSUE TITLE
Failed Watcher Cannot Complete

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2638]
Description

1. Create a Screen with a Watcher that cannot complete properly
1. Preview the Screen and run the Watcher

**Result:**

The "something went wrong" modal appears but never goes away, preventing the rest of the Screen from being interactive.

PRD: If the script fails, the screen continues to allow interaction. If the mode was synchronously, an error modal can be presented to show that an unexpected error occurred but still allow interaction afterwards.

**Comment by marcoAntonioNina** [comment]
need https://github.com/ProcessMaker/screen-builder/pull/460
