### ISSUE TITLE
Watcher scripting timeout not working

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2639]
1. Create a script with a 5 second timeout
1. Create a Watcher on a Screen that references the 5 second script
1. Run the Screen via preview or by running it in a Process

**Result:**

Script continues to run even after the timeout has been reached.

It could be the script has successfully completed, but the Watcher does not know, and has not received the completed returned data.

**Comment by caleeli** [comment]
Can not be replicated, the only one scenario in which the response do not arrive is when the broadcasting is not properly configured
