### ISSUE TITLE
Watcher Syntax Error with Multiple Variables

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2641]
i was trying to use the watchers to fill more form out with multiple fields at once (and not have to use calc prop for each individual field). thus i used the variable naming convention of [watcher output object name].[variable name] as the name of my variable in my form.

this works great in preview mode and does exactly what is expected. however, there is an error so i can't save the screen due to "syntax" error on the variable name. please see screen shot.

![image](https://user-images.githubusercontent.com/535300/70172819-5c687600-1686-11ea-8bbf-17092dbf839d.png)

**Comment by marcoAntonioNina** [comment]
the problema cannot be reproduced.
![image](https://user-images.githubusercontent.com/1747025/70339390-26152d00-1825-11ea-89b4-a81cde72c2fe.png)

**Comment by velkymx** [comment]
I believe this is resolved. Will reopen if comes up again.
