### ISSUE TITLE
Watchers Running without Variable Interaction

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2642]
**Description**

1. Create Screen with at least one Watcher control set to run asynchronously
1. Press the submit button without filling out the watched form variable

**Result:**

Even though the watched variable is never set, the script will still run on submit. Theoretically this can be considered a user error.

**Expected Result**

The script shouldn't be triggered until the variable changes. If it is not interacted with, it should not run.

**Comment by velkymx** [comment]
Another usecase:

1. Create a Screen with a Watcher variable set to a checkbox control
1. Preview the Screen

**Result:**

Instead of waiting for user input to modify the checkbox, the Screen immediately starts the Watcher.

**Expected:**

Screen waits for user interaction to check/uncheck the checkbox, and then starts the Watcher.

**Comment by marcoAntonioNina** [comment]
need https://github.com/ProcessMaker/screen-builder/pull/464
