### ISSUE TITLE
Watcher Script Config Not Saving

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2643]
1. Create a Screen
1. Configure a watcher, and put the following into "Script Configuration"
```{"dataMapping":["foo":"bar"]}```
1. Save the watcher, save the Screen, reload the page
**Re-open** the watcher

**Result:**

The configuration reverts to the default

```{"dataMapping":[]}```

**Comment by marcoAntonioNina** [comment]
need https://github.com/ProcessMaker/screen-builder/pull/457
