### ISSUE TITLE
Watcher continually updating

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2645]
Found in: Latest code, run locally

Create a Screen with a watcher, and set the watched variable to be a select list control
Choose anything from the select control

**Result:**

If async is chosen, no "is running" modal appears, and the data preview results continually update. If sync is chosen, the modal appears and disappears with each run. In either case, it will not stop until the page is reloaded.

**Note:**

I've attached what.json, which is the screen used for this bug. You'll still need to set up the watcher, though. I've also attached two videos of this occurring on both sync/async.

[what.json.txt](https://github.com/ProcessMaker/processmaker/files/3928370/what.json.txt)

https://www.dropbox.com/s/eqbtolgoa7vm02x/sync.mp4?dl=0

https://www.dropbox.com/s/s6vmbu9jca5ooea/async.mp4?dl=0

Here is some basic LUA code to run as a script:

```math.randomseed(os.time())
principal = data["principal"]
interest = (math.random (1, 25)/100)
time = math.random (1, 25)

total = principal*(1 + interest/1)^(1*time) --Yearly compounding interest
compoundResult = math.floor(total * 100 + 0.5) / 100 --This tries to help with rounding

return {principal=principal,
    interest=interest,
    time=time,
    compoundResult=compoundResult, interestEarned=compoundResult-principal}
```

**Comment by marcoAntonioNina** [comment]
need https://github.com/ProcessMaker/screen-builder/pull/462
