### ISSUE TITLE
Where is Process Objects in current version?

### ISSUE THREAD

**Issue by cyberiums** [ProcessMaker/processmaker#2655]
Hi,

I tried Bitnami Processmaker Community edition, and it has Process Objects like this image.
![image](https://user-images.githubusercontent.com/50774706/70586029-0b7be480-1b94-11ea-85ee-17e841301ab1.png)

But same is not there in the current version on github. Also the UI is very different. Can someone help please for how to access Process Object in current version.

**Comment by cyberiums** [comment]
Any help please?

**Comment by nolanpro** [comment]
@cyberiums ProcessMaker 4 does not have a process objects section. The same functionality can be found on the left menu on the designer tab and in the process modeler.

**Comment by tdondich** [comment]
@cyberiums Please also refer to our documentation at https://processmaker.gitbook.io/processmaker/ 
A lot has changed in this version.
