### ISSUE TITLE
RTL Feature

### ISSUE THREAD

**Issue by AMINEDGE** [ProcessMaker/processmaker#2661]
Hi, I'm Persian and I wanted to change the theme layout to RTL and also the date format to Jalali, should I change the source from scratch or is there any easier way or some sort of plugin to do that?

**Comment by nolanpro** [comment]
@AMINEDGE The date format can be set in the `.env` file's `DATE_FORMAT` variable. Currently we do not support RTL but since we're using common open source packages like vue-bootstrap, it shouldn't be too hard to implement. Perhaps you could submit a PR

**Comment by AMINEDGE** [comment]
@nolanpro I somehow managed changed the style to RTL but for date format, jalali calendar is something different from gregorian (default calendar and datepicker), in JavaScript I use moment-jalaali but as the form builder is kinda advanced system, I think it's kinda heavy task to implement the jalaali calendar

**Comment by tdondich** [comment]
We're working on documentation to create custom themes and how to create custom screen builder controls. Keep an eye out so we can look at building a custom screen builder control for RTL support.
