### ISSUE TITLE
Masking Fails in Multicolumn

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2685]
1. Add a Line Input control to a form
2. Configure the input to be a "Currency" Data Type
4. Preview the form, note it properly shows the 3 letter currency code
6. Move the input inside a table
8. Preview the form

**Result:**

Input control loses the currency code.

**Expected:**

The currency overlay remains even though the input is inside a table.

**Comment by caleeli** [comment]
@nolanpro I forgot to add and use the Input-maked component inside the multicolumn component (src/components/renderer/form-multi-column.vue)

**Comment by nolanpro** [comment]
@caleeli yeah I saw that. There's also some console errors for percentage that I'm trying to fix as part of this issue
