### ISSUE TITLE
Collections Data Connector

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2689]
When creating a new collection, the collections is no longer registering a Data Connection properly.

**Comment by velkymx** [comment]
Once collections and data sources are installed a new Job is installed  and the queue should be restarted.

**Comment by nolanpro** [comment]
Fixed in
https://github.com/ProcessMaker/package-collections/pull/164
https://github.com/ProcessMaker/package-data-sources/pull/38
