### ISSUE TITLE
Multipage Variables Colliding 

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2690]
1. Create a form-type Screen with multiple pages
2. Put at least one Line Input control on each page, any data type
3. Preview the form, try to enter unique data for each input on each page

**Result:**

Line Input controls for multi-page forms are broken, the inputs just carry over whatever was filled in from the prior page to the new page.

**Expected:**

Fields clear out for each field.

**Video**

https://www.dropbox.com/s/obq9wqno564qpr8/multipage-input-values.mp4?dl=0

**Comment by velkymx** [comment]
If two variables have the same name, they should have the same value and be reactive

**Comment by nolanpro** [comment]
This appears to be fixed by https://github.com/ProcessMaker/screen-builder/pull/474
