### ISSUE TITLE
Record List Broken

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2692]
The record list doesn't accept new data correctly, editing data is inconsistent and broken. Adding new data after already using the record list the form has the previous values. Data is escaping the parent object in the JSON.

Can we fix this so it works and add a test to ensure CI catches if it's broken

https://www.dropbox.com/s/cxoijjvo9eudztr/record-list-fail.mov?dl=0

**Comment by marcoAntonioNina** [comment]
It is solved with the ticket https://github.com/ProcessMaker/screen-builder/pull/474
