### ISSUE TITLE
WARNING: USER'S ACCOUNT HAS EXPIRED

### ISSUE THREAD

**Issue by arad56** [ProcessMaker/processmaker#2704]
Hello
I can't get login to the PM through Admin. I'm receiving the message mentioned in topic subject. how can I fix it? it is installed as standalone in Windows 
Thanks in advance.
![2020-01-04_15h48_53](https://user-images.githubusercontent.com/59505604/71766012-6c3ada80-2f10-11ea-9626-7642404bf388.jpg)

**Comment by tdondich** [comment]
Hi @arad56 , unfortunately, this isn't the space for ProcessMaker 3.  However, there's a known issue in PM3 where the expiration date of admin is 2020-01-01.  Update your database to manually set it to something farther in the future and you should be good to go.
