### ISSUE TITLE
Video Tutorials

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2716]
- [x] How to populate record lists with data from collections [@danloa ] [[download](https://drive.google.com/file/d/18JOqswohDnwFR_GJe1EJJpshqlyIa-gv/view?usp=sharing)]
- [x] How to set up SAML SSO (talk to Daniel) [@ryancooley] [[download](https://drive.google.com/open?id=1l0QQObMj70ZrWHNO_h6QrhfFw6CoYjRh)]
- [x] How to start a Request via the API (get example) [@nolanpro] [[download](https://drive.google.com/file/d/1aNp65i3qZbLbM6LnhTa5ehq3izmGgLgm/view?usp=sharing)]
- [x] How to integrate external app with Script Task [@caleeli ] [[download](https://www.dropbox.com/s/vhyhwbcf4sxnduo/script_task_external_api_node.mov?dl=0)]
- [x] How ProcessMaker stores data [@nolanpro] [[download](https://drive.google.com/file/d/1MbrSiT93xe0KBpqFjT0g0IRkAxRdIeV1/view?usp=sharing)]
- [x] How to update Request data using the API [@ryancooley] [[download](https://drive.google.com/open?id=1mhoq-ZNM3gQE1hNCodUsgc8zIfJKkpXV)]
- [x] Using the PM4 API in a script via the SDK [@caleeli ]

**Comment by PMQABen** [comment]
[Zip File: Multi-Page-Screen.mp4](https://github.com/ProcessMaker/processmaker/files/4033293/Multi-Page-Screen.zip)

**Comment by tdondich** [comment]
Guys, this list is incorrect based on our internal google sheet.  Will have @ryancooley update the ticket with the right list.

**Comment by ryancooley** [comment]
Previous list for future reference:

- [x] How to add logo to Screen
- [ ] How to call Collection endpoints from Script Tasks
- [ ] How to call subprocess in a process [In progress - David]
- [x] How to create Screens with multiple pages
- [ ] How to create SLAs with Saved Searches
- [ ] How to populate a Screen with a Script
- [ ] How to use computed properties (current date)
- [ ] How to use intermediate web entry 
- [ ] How to use PMQL
- [ ] How to use record lists
- [ ] How to use Select List control [In Progress - Dante]

**Comment by nolanpro** [comment]
https://drive.google.com/file/d/1aNp65i3qZbLbM6LnhTa5ehq3izmGgLgm/view?usp=sharing

**Comment by velkymx** [comment]
Advanced forms
https://www.dropbox.com/s/gr8cmuy0g5aa2r9/advanced-form-datatable.mov?dl=0
Watchers
https://www.dropbox.com/s/y9o8jcirf6ala3o/Watcher_PM4_video.mp4?dl=0

**Comment by velkymx** [comment]
Using the API in a script

**Comment by velkymx** [comment]
https://www.dropbox.com/s/vhyhwbcf4sxnduo/script_task_external_api_node.mov?dl=0

**Comment by velkymx** [comment]
New video: Export the BPMN via the API and import it into Camunda.

**Comment by danloa** [comment]
Use SelectList with Collections as DataSource

https://drive.google.com/file/d/1XJFUkvNPcWgDO-kcWbRXQJ3xZ40A3CrC/view?usp=sharing

**Comment by cybrpimp** [comment]
How about an installation video that works.  So far all install methods I've seen for PM4 do not work.

**Comment by velkymx** [comment]
Check out how to work with homestead. https://www.youtube.com/watch?v=0AKMvpbMoH0
