### ISSUE TITLE
Screen Import Fails

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2719]
https://www.dropbox.com/s/bcclxvcgshuoqo4/screen-import-fails.mp4?dl=0

**Comment by danloa** [comment]
@velkymx this issue was resolved in screen-builder
**https://github.com/ProcessMaker/screen-builder/issues/489**
Using the current develop branch, no errors are generated. Anyway it will be better if we can have the exported file of the screen that generated the problem.

**Comment by velkymx** [comment]
Pending new screen builder
