### ISSUE TITLE
Data Connector POST fails

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2747]
Saving to a collection via data connector 500s

![image](https://user-images.githubusercontent.com/535300/72548692-0d486000-3844-11ea-927e-6093ce76b38b.png)

https://staging-pm4.processmaker.net/modeler/27

**Comment by caleeli** [comment]
The problem was that the body of the POST method was empty. The fix was to complete that configuration:

![image](https://user-images.githubusercontent.com/8028650/72566734-bca82580-388a-11ea-976c-b556c7a13ca2.png)
