### ISSUE TITLE
Package: Dynamic Home Page

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2758]
Allow user to specify default login page. Some sort of “Make my home” button or icon for major areas so that when a user logs in again, it redirects immediately to that page.

We need this to be internally reportable (via a SQL query) so we can determine the use of this feature so we can expand later

https://github.com/ProcessMaker/package-dynamic-homepage

**Comment by danloa** [comment]
Will be resolved in
https://github.com/ProcessMaker/package-dynamic-homepage/issues/2
