### ISSUE TITLE
Visibility Rules for IN

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2784]
For visibility you would use "in" / "not in". Example:

Select List: multiple selections enabled, variable name "multiSelect"

```Data source:
[
  {"value":"yes","content":"yes"},
  {"value":"no","content":"no"},
  {"value":"idk","content":"i don't care"}
]
```

Visibility rule to display something when "yes" is chosen:

`"yes" in multiSelect`

Visibility rule to display something when "yes" is not chosen:

`"yes" not in multiSelect`

HOWEVER, it looks like "not in" is not working.

**Comment by sanjacornelius** [comment]
Currently, the visibility input does not support [ValidatorJS](https://www.npmjs.com/package/validatorjs#not_infoobar) expressions, which includes the `Not In` rule.

We are using the [expr-eval ](https://www.npmjs.com/package/expr-eval) library to evaluate the expressions. It supports their own [expressions](https://www.npmjs.com/package/expr-eval#expression-syntax) as well as native [JavaScript expressions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators).

There are two ways to replicate the ValidatorJS `Not In` rule.
1. **Expr-Eval:**
`not("yes" in mulitSelect)`

2. **Native JavaScript:**
`"yes" in multiSelect == false`

**Video:**
https://www.dropbox.com/s/mvax20f9cxmknk5/Edit%20Screen%20-%20ProcessMaker.mp4?dl=0
