### ISSUE TITLE
Importing Invalid BPMN

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2787]
Add validation to the file upload in the New Process BPMN import. Should allow .bpmn and .xml files only. If the file is upload and found to be invalid, then the server should notify the user of the explicit message.

**Comment by sanjacornelius** [comment]
Can not reproduce see the video and attached invalid BPMN

https://www.dropbox.com/s/6pzn6os5jza7eis/Processes%20-%20ProcessMaker.mp4?dl=0

[invalid-bpmn.bpmn.txt](https://github.com/ProcessMaker/processmaker/files/4156819/invalid-bpmn.bpmn.txt)

**Comment by nolanpro** [comment]
Figured it out. The error is when there this invalid XML, not just invalid BPMN
