### ISSUE TITLE
Failed Request Messaging

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2788]
Steps to Reproduce:

1. Create a process with a exclusive gateway
2. set wrong expression in the outgoing sequences flows
3. Run a case through the gateway
4. See a 500 Error (Request failed with status code 500)

Edit: Alan mentioned this happens when the 2 expressions are the same

**CURRENT BEHAVIOR:**

"Request failed with status code 500" error is shown when there are wrong expressions set for an exclusive gateway. Also note that once the issue happened you can't continue with the request even after the issue got fixed from the designer.

**Expected Behavior:**

500 error is too generic, users should see something more specific like "Wrong expressions set for gateway" or "Any expression was evaluated as true, contact your administrator" or something else. You should be able to continue with the request once the issue got fixed from the designer

**Comment by nolanpro** [comment]
I'm not able to reproduce when starting directly to the gateway or via a script.
- Syntax errors are surfaced correctly
- Expression not valid error surfaced correctly when the variable is not set (Direct start to gateway)
- When the expressions are the same and they match, it picks the first one
- When the expressions are the same and they don't match, the processes stays in an indefinite In Progress sate.
![image](https://user-images.githubusercontent.com/2546850/73200242-3e9a1900-40eb-11ea-992e-147f909d36c0.png)

**Comment by PMQABen** [comment]
Still occurs, the expression needs to be obviously invalid. Attached zip file of a process.
[1-Failed Request Messaging.json.zip](https://github.com/ProcessMaker/processmaker/files/4118848/1-Failed.Request.Messaging.json.zip)
