### ISSUE TITLE
How can i install this without composer?

### ISSUE THREAD

**Issue by cristo1985** [ProcessMaker/processmaker#2795]
Hi,
i would want install this project without using the damned composer? I am used to installing php projects with a simple copy, paste and configure. I don't like composer. Is it possible to obtain an easily installable and configurable version? Thank you.

**Comment by tdondich** [comment]
Sorry @cristo1985 , but if you're using the open source version, we'll assume you have a buildchain available for installation of required 3rd party packages.  We, at this time, don't provide some open source installer and do not have plans to do so.  If you want a trial of ProcessMaker in the cloud without having to deal with building and installing packages/etc, reach out to our team and we can get you started with an eval.
