### ISSUE TITLE
selected element hidden on screen builder 

### ISSUE THREAD

**Issue by bmackley** [ProcessMaker/processmaker#2798]
**Describe the bug**
In a screen with a table, when an element is selected that is larger than the table cell, the delete option for the element is hidden behind the other cell's contents. 

**To Reproduce**
1. Go to screen builder. 
2. Create a table with 6 cells with width of 2
3. Put content in the cells
4. select one of the first couple of cells
5. The delete button is hidden behind the contents of the other cells

**Expected behavior**
The delete button should be selectable. 

**Screenshots**
![image](https://user-images.githubusercontent.com/6541727/73363208-4a661680-4276-11ea-968b-cc7c68a5c95c.png)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser Chrome
 - Version 79

**Comment by velkymx** [comment]
This is resolved in GA
