### ISSUE TITLE
Required fields on record list preventing form submission

### ISSUE THREAD

**Issue by bmackley** [ProcessMaker/processmaker#2799]
**Describe the bug**
A field on a record list marked required prevents a form from submitting. 

**To Reproduce**
1. Create a form with a record list. 
2. Make a field on the record list required. 
3. Try to submit the form. 

**Expected behavior**
The record should only be added when the required fields are filled.  The submit button for the form should also work even if a record hasn't been added. 

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Comment by velkymx** [comment]
This is resolved
