### ISSUE TITLE
Unable to run NPM in PROD mode

### ISSUE THREAD

**Issue by Kookster310** [ProcessMaker/processmaker#2802]
**Describe the bug**
After running npm install, you are unable to run npm run prod. It gets stuck at 91% then eventually fails with a memory error:
`> @ production /opt/processmaker
> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

 91% additional asset processing

<--- Last few GCs --->

[4519:0x45b4a70]   616597 ms: Scavenge 1976.2 (2050.6) -> 1975.4 (2050.6) MB, 14.9 / 0.0 ms  (average mu = 0.133, current mu = 0.004) allocation failure
[4519:0x45b4a70]   616614 ms: Scavenge 1976.3 (2050.6) -> 1975.5 (2050.9) MB, 14.4 / 0.0 ms  (average mu = 0.133, current mu = 0.004) allocation failure
[4519:0x45b4a70]   619112 ms: Mark-sweep 1976.4 (2050.9) -> 1973.6 (2050.9) MB, 2495.5 / 0.1 ms  (average mu = 0.226, current mu = 0.325) allocation
failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x1376259]
Security context: 0x0c39170408a1 <JSObject>
    1: _clone [0xb17fb433599] [0x17bad94404a9 <undefined>:~444] [pc=0xe31c25442ee](this=0x1e8bd7769a81 <AST_Sequence map = 0x1bfedc9271c1>,0x17bad9440631 <true>)
    2: clone [0xb17fb433e51] [0x17bad94404a9 <undefined>:456] [bytecode=0x3cd8af00aba9 offset=7](this=0x1e8bd7769a81 <AST_Sequence map = 0x1bfedc9271c1>,0x17bad9440631 <true>)
    3: /* anonymous */ [0x1...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

Writing Node.js report to file: report.20200129.222003.4519.0.001.json
Node.js report completed
 1: 0x9dab70 node::Abort() [node]
 2: 0x9dbd26 node::OnFatalError(char const*, char const*) [node]
 3: 0xb3b18e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb3b509 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xce68a5  [node]
 6: 0xce6f36 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node]
 7: 0xcf2dca v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 8: 0xcf3cd5 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xcf66e8 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [node]
10: 0xcbd017 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType) [node]
11: 0xff307b v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
12: 0x1376259  [node]`

**To Reproduce**
1. Download and extract release: https://github.com/ProcessMaker/processmaker/releases/download/v4.0.0/processmaker4-prod.tar.gz
2. Run npm install
3. Run npm run prod

**Expected behavior**
Should finish compiling javascript/node_modules.

**Desktop (please complete the following information):**
 - Tested in amazon linux. 
 - Nolan confirmed locally in vagrant Ubuntu image and OSX.

**Comment by todfox** [comment]
I also have this problem.

**Comment by velkymx** [comment]
Use the following commands:

```composer install --no-dev ;
npm install
export NODE_OPTIONS="--max-old-space-size=4096"
npm run prod
```
