### ISSUE TITLE
JSON Schema GUI

### ISSUE THREAD

**Issue by danloa** [ProcessMaker/processmaker#2807]
https://github.com/ProcessMaker/package-vocabularies/releases/tag/v2.1.1

**Comment by danloa** [comment]
A couple of open source  editors support JSON schema  configuration

https://github.com/tangram-js/json-schema-editor

![image](https://user-images.githubusercontent.com/14875032/73765316-c1098500-474a-11ea-859b-14fe7b1f11bb.png)

https://github.com/yourtion/vue-json-ui-editor

![image](https://user-images.githubusercontent.com/14875032/73765400-dda5bd00-474a-11ea-9b68-dfee8f366760.png)


The last one is more user friendly but needs a Json schema  for editing a json. So we need to find the "meta json schema" for json schema

**Comment by velkymx** [comment]
I like this one too 
![image](https://user-images.githubusercontent.com/535300/73867833-35503100-47fc-11ea-8088-a1981fcd4582.png)

Or more traditional

![image](https://user-images.githubusercontent.com/535300/73867861-41d48980-47fc-11ea-8af8-49237f60cfdd.png)

**Comment by velkymx** [comment]
From TD - we need to support inheritance 

![image](https://user-images.githubusercontent.com/535300/73985973-62324000-48f1-11ea-8c8b-f1bc2eae1119.png)

**Comment by PMQABen** [comment]
Console error upon page load:
```
[Vue warn]: Property or method "showingVisualEditor" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.
(found in <Root>)

[Vue warn]: Property or method "showingCodeEditor" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.
(found in <Root>)

[Vue warn]: Invalid handler for event "click": got undefined
(found in <Root>)

[Vue warn]: Unknown custom element: <tree-editor> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
(found in <Root>)
```

Visual interface does not work. Trying to use the code tab throws more console errors:
```
[Vue warn]: Error in nextTick: "TypeError: Cannot read property '_wrapper' of undefined"

TypeError: Cannot read property '_wrapper' of undefined
    at remove$2 (vendor.js?id=379ed5b61329c34096d6:117991)
    at updateListeners (vendor.js?id=379ed5b61329c34096d6:112652)
    at Array.updateDOMListeners (vendor.js?id=379ed5b61329c34096d6:118004)
    at patchVnode (vendor.js?id=379ed5b61329c34096d6:116732)
    at updateChildren (vendor.js?id=379ed5b61329c34096d6:116611)
    at patchVnode (vendor.js?id=379ed5b61329c34096d6:116737)
    at updateChildren (vendor.js?id=379ed5b61329c34096d6:116611)
    at patchVnode (vendor.js?id=379ed5b61329c34096d6:116737)
    at updateChildren (vendor.js?id=379ed5b61329c34096d6:116611)
    at patchVnode (vendor.js?id=379ed5b61329c34096d6:116737)
```
Code tab covers up the cancel and save buttons:
![image](https://user-images.githubusercontent.com/28575916/78173742-0675c600-740d-11ea-9fdc-dada45984e11.png)

Not ready for QA.

**Comment by PMQABen** [comment]
Switching between Code and Visual after loading a vocabulary causes the + add option to be removed:
![image](https://user-images.githubusercontent.com/28575916/78703184-a4123f00-78be-11ea-982d-d6d58cbb78c6.png)
A related console error appears if the user tries to click the trash icon in this situation:
```
[Vue warn]: Error in v-on handler: "TypeError: Cannot read property 'children' of null"
found in
---> <TreeItem>
       <TreeEditor>
         <Root>
```
When adding a new vocabulary entry, if the user moves from Visual, to Code, and back to Visual, the value of the vocabulary entry is removed.

Unable to save new vocabularies. Clicking the save button says "The vocabulary was saved", but when you go back into it, all new entries are gone.

**Comment by PMQABen** [comment]
Kelly verified that trying to save vocabulary edited solely via the "Code" tab also does not work. Importing JSON files also does not work, though when loading the page it obviously shows the imported key/values:
```
{
	"data": [{
		"id": 3,
		"user_id": 1,
		"title": "ddddddd",
		"description": "dddddddd",
		"content": "{\"name\": \"processmaker\/processmaker\",\"version\": \"4.0.0\",\"description\": \"BPM PHP Software\",\"keywords\": [\"php bpm processmaker\"]}",
		"created_at": "2020-04-07T21:57:48+00:00",
		"updated_at": "2020-04-07T21:57:48+00:00"
	}],
	"meta": {
		"filter": null,
		"sort_by": "title",
		"sort_order": "asc",
		"count": 1,
		"total_pages": 1,
		"current_page": 1,
		"from": 1,
		"last_page": 1,
		"path": "http:\/\/bpm4.local.processmaker.com\/api\/1.0\/vocabularies",
		"per_page": "1000",
		"to": 1,
		"total": 1
	}
}
```

**Comment by PMQABen** [comment]
No new code has been committed, JSON GUI still not working.

**Comment by danloa** [comment]
@PMQABen  The observations have been fixed. About how the editor works, in the following zip there is a video that shows how to add fields and use the inheritance in a  JSON Schema.

[Peek 2020-04-20 15-37.zip](https://github.com/ProcessMaker/processmaker/files/4505839/Peek.2020-04-20.15-37.zip)

**Comment by PMQABen** [comment]
Still losing entries when saving. Video: [gui1080.mp4.zip](https://github.com/ProcessMaker/processmaker/files/4511598/gui1080.mp4.zip)

---
When trying to save a Date field, the following console error is thrown:
```
No valid results for anyOf {
0: Enum failed, enum: ["array","boolean","integer","null","number","object","string"], data: "date" at #->properties:properties->additionalProperties:newAttribute_6->$ref[#]->properties:type->anyOf[0]->$ref[#/definitions/simpleTypes]
1: Array expected, "date" received at #->properties:properties->additionalProperties:newAttribute_6->$ref[#]->properties:type->anyOf[1]
} at #->properties:properties->additionalProperties:newAttribute_6->$ref[#]->properties:type
```
Doesn't matter if I enter the date as `01-01-2001`, `2001-01-01`, `01-01-2001T00:00:00+00:00`, or `2001-01-01T00:00:00+00:00`

---
If changing the mainSchema "length or inherit" to an existing Vocabulary that is empty, the **+** add button disappears and will not display again, even if the you switch back to "No inheritance"

**Comment by PMQABen** [comment]
Just realized: A user can import a JSON vocabulary file, but they cannot export.
