### ISSUE TITLE
Add Process Cannot Complete Check

### ISSUE THREAD

**Issue by caleeli** [ProcessMaker/processmaker#2809]

**Comment by PMQABen** [comment]
Requires: ProcessMaker/modeler#1126
Package: https://github.com/ProcessMaker/package-process-optimization

**Comment by PMQABen** [comment]
[purchase order.spark.txt](https://github.com/ProcessMaker/processmaker/files/4505061/purchase.order.spark.txt)
[Send_sms_test.spark.txt](https://github.com/ProcessMaker/processmaker/files/4505063/Send_sms_test.spark.txt)
[QA Test-Start Event.json.txt](https://github.com/ProcessMaker/processmaker/files/4505134/QA.Test-Start.Event.json.txt)

These processes fail the simulation test, but I can't tell why. The SMS Test process has a not completed failure at the first task, even though it's obviously connected to the start event. The "QA Test Start Event" process I know works properly, but has multiple failures and warnings.
