### ISSUE TITLE
UTF-8 Characters in firstname and lastname

### ISSUE THREAD

**Issue by Sajad2010** [ProcessMaker/processmaker#2814]
1- Go to Admin > Users
2- Click on Edit Icon for an user.
3- Change firstname and lastname to UTF-8 (for example arabic or persian,   Fistname: نام Lastname: تست) 
4- Click on Save,
5- Refresh page now or do step 1 & 2 , all fields is empty ! (cannot show utf8 characters)

**Comment by danloa** [comment]
All PHP string function don't handle multi byte strings properly. It should be good to search in the code for places where this can be happening:

https://www.php.net/manual/en/intro.mbstring.php

**Comment by Sajad2010** [comment]
Thank you,
Same Problem at /profile/edit
