### ISSUE TITLE
Data Connector Label

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2820]
Anywhere a Data Connector can be selected or show, we need to make sure we don't show the term Data Source, we've renamed it to Data Connector. Still seeing it in parts of the UI. 

![image](https://user-images.githubusercontent.com/535300/73782847-95d16680-4747-11ea-8fc3-aa01879538ff.png)

Remember a Data Source could be a Data Connector (or Request Data, etc)

**Comment by sanjacornelius** [comment]
@velkymx found some text that needed to be updated but I having trouble locating the above-pictured UI. Is there an additional package that is installed for that screen?

**Comment by velkymx** [comment]
> @velkymx found some text that needed to be updated but I having trouble locating the above-pictured UI. Is there an additional package that is installed for that screen?

I believe that is in the Watchers UI
