### ISSUE TITLE
Category Permissions Trampling Processes

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2821]
1.  Create a user, assign them to a group
1.  Enable the following permissions to the group:
1.  Create Processes
1.  Edit Processes
1.  View Processes
1.  Log in as the user, go to the main designer page

Result:

Processes appear as expected, but an alert banner appears stating "this action is unauthorized". It looks like this is because PM4 is trying to make a call to view Process Categories, which is returning 403.

Please make sure that this is also fixed for Screens and Scripts

**Comment by PMQABen** [comment]
So the fix is: _"makes it so that if you have permission to edit or create a process/script/screen, you can also view its categories."_

With this fix in place, do we still need the Create/Edit/View/Delete Categories permissions?

**Comment by nolanpro** [comment]
@PMQABen yeah I think we still need those permissions. Although it's pretty granular, some admin might want some people to create/edit things without messing with categories
