### ISSUE TITLE
Test Screen with Vocabulary

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2846]
As a screen designer I want to be able to load a vocabulary to test that my screen satisfies the requirements in the vocabs JSON schema. This should not save as part of the screen, but rather be used in the screen preview when you submit the form.

**Comment by velkymx** [comment]
This needs to be moved into the Vocabulary package

**Comment by PMQABen** [comment]
File commit https://github.com/ProcessMaker/package-vocabularies/pull/20 for vocab package issue https://github.com/ProcessMaker/package-vocabularies/issues/10 does not seem to work. Able to select vocabulary, but there is no data input pre-population and it does not seem to validate the screen in preview mode.

**Comment by nolanpro** [comment]
Waiting on https://github.com/ProcessMaker/processmaker/issues/2807

**Comment by nolanpro** [comment]
@PMQABen fixed error display in https://github.com/ProcessMaker/package-vocabularies/pull/23 Default values is a known issue https://github.com/ProcessMaker/package-vocabularies/issues/22
