### ISSUE TITLE
Self Assignment Not Assigning

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2869]
Self-service assignment is only assigning the task to one user, but not the whole group. Video included.

https://www.dropbox.com/s/3neme0qtu7w2j6j/self_service_assignment.mp4?dl=0

**Comment by marcoAntonioNina** [comment]
the list must be self-service
there is an option in the sidebar for self-service
![image](https://user-images.githubusercontent.com/1747025/74532627-0aee2a00-4f06-11ea-9de9-2e7c906bbc2f.png)
