### ISSUE TITLE
Double Dropdowns

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2873]
I am seeing double arrows in dropdowns. This is caused by an incorrect CSS class being applied the select elements.

![image](https://user-images.githubusercontent.com/535300/74671923-040f2380-5161-11ea-9adc-4d5328ae9e78.png)

**Comment by johnblackspear** [comment]
Hi @velkymx 

Having trouble reproducting this - can you tell me more about the steps and environment you used to create the screenshot above?

**Comment by johnblackspear** [comment]
Still not able to reproduce, unfortunately. Screenshot running modeler standalone, latest develop, Chrome 80.0:

<img src="https://user-images.githubusercontent.com/28595383/75821409-1e1e4800-5d96-11ea-8eb3-4b795334c116.png" width="450"/>

**Comment by johnblackspear** [comment]
Also seems to work in core:

<img src="https://user-images.githubusercontent.com/28595383/75821618-7ead8500-5d96-11ea-8f1d-a4bbc819047f.png" width="600" />

**Comment by velkymx** [comment]
Looks like its fixed. Will reopen if we find more.
