### ISSUE TITLE
Request Form History Embedded Forms Empty

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2874]
When looking a screen review in the request detail, clicking expand shows the form as it was during the execution, however the embedded forms are blank.

**Comment by caleeli** [comment]
Steps to reproduce in issue:

- Create a sub screen
- Create a main screen
- Add the sub screen into the main, and setup its data variable name
- Assign the main screen into a process
- Complete the process
- Go to history

**Comment by ZLTM** [comment]
Seems to be working
![image](https://user-images.githubusercontent.com/7957742/75777500-77ea2800-5d2c-11ea-8e0b-89803c1ca030.png)
