### ISSUE TITLE
Environment Vars Text Limit

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2875]
The environment variable shouldn't have a text limit. I need to be able to store longer data, such as bearer tokens, and currently I am limited.

**Comment by johnblackspear** [comment]
Hi @velkymx 

Can you give some reproduction steps and a description of the error you are seeing? From looking at the rules for environment variables I don't see any max length defined:

![image](https://user-images.githubusercontent.com/28595383/75711245-f65bb100-5cbd-11ea-8b58-0d5b9fd4dbaa.png)

**Comment by velkymx** [comment]
I believe the issue is in the limitation of the text input in the UI

**Comment by sanjacornelius** [comment]
@velkymx to clarify is are you receiving a 500 error when you are trying to store longer data or are you receiving a different error?

<a href="https://www.loom.com/share/dae04a0705e049038a431d4b72d6db13"> <p>Envoirment Variables Text Limit - Watch Video</p> <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/dae04a0705e049038a431d4b72d6db13-with-play.gif"> </a>
