### ISSUE TITLE
Audit modeler inspectors.

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2877]
This issue is for the Nayra team. Please review all modeler elements and confirm or notate in this issue any issues or missing configuration.

**Comment by velkymx** [comment]
In the intermediate timer event of type cyclic for the weekly option, there is no option to choose the day of the week

**Comment by danloa** [comment]
Found Issues:
- **Intermediate Time Events->Cyclical** ==> It should show  options similar to  Timer Start event.

**Comment by caleeli** [comment]
- Can not create message flows from End Message Events to Start Message Events: https://github.com/ProcessMaker/modeler/issues/1105

**Comment by caleeli** [comment]
- Implementation of Terminate End Event to close all the pending tasks and complete the process
