### ISSUE TITLE
Mark Required Field with Asterisk

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2879]
Anywhere we are requiring a field in the UI (not screen forms)  such as modals, the required fields need to be identified by an Asterisk. Some are, some are not.

**Comment by PMQABen** [comment]
Description Field for editing a screen is missing an asterisk. Screen Builder checks are waiting on 0.22.

**Comment by ZLTM** [comment]
Still need to add an asterisk on:
-  groups > group members > add user > users
-  groups > group details > name
-  queue management > monitoring > monitor tag > tag name
-  Process > create process > category
-  Process > configuration > description
-  Script > create script > category
-  Script > configuration > category
-  Script > Copy > category
-  Screen > create script > category
-  Screen > configuration > category
-  Screen > Copy > category

**Comment by PMQABen** [comment]
Adding in "Redirect URL" when creating an Auth Client.
