### ISSUE TITLE
ProcessMaker install for production

### ISSUE THREAD

**Issue by GaneshKandu** [ProcessMaker/processmaker#2880]
``Question``
How can i install open source ProcessMaker on production ?

**Comment by velkymx** [comment]
Download the TAR file in the release notes. Untar the file on your web server and then use the Composer commands to install the core libraries. Afterwards the ProcessMaker 4 application will be available if you point your web server to the public directory. 

For more information visit: 

https://laravel.com/docs/5.8/installation

**Comment by chau-huu** [comment]
Hi 
After Downloading the TAR file in the release notes. and decompressed the file on your web server and then used the composer's commands to install the basic libraries. Then, the ProcessMaker 4 application will be available if you point your web server to the public directory. 
I connect well to the application yet I encounter the following error:
"Sorry! API failed to load
Something went wrong. Try refreshing the application."

Thank you

**Comment by JackWangz** [comment]
Hi @chau-huu 
Did you resolve this problem?
I got the same error as well and tried to figure out the causes for that.
