### ISSUE TITLE
Processmaker 4 installation using Postgres as the Processmaker DB

### ISSUE THREAD

**Issue by ambatshri** [ProcessMaker/processmaker#2885]
I've installed processmaker 4.0 / develop branch using the steps given below in README.md
I want to use postgres as the only database for setting processmaker up. Can anyone lemme know the steps to do it. I've tried changing the database config files. Forcing it to use pgsql as the database driver, still it uses mysql driver. Changed the connections.processmaker.driver to pgsql in config/database.php 

Failed to connect to DATA connection. Ensure the database exists. Check your credentials and try again. {"driver":"mysql","host":"127.0.0.1","port":"5432","database":"processmaker","username":"****","password":"****","schema":"","engine":"InnoDB"}
 

**To Reproduce**
1. Go to 'config/database.php' and change the driver for processmaker to pgsql. 
2. Run the artisan processmaker:install command
3. Provide necessary credentials.

**Expected behavior**
Running processmaker using the Postgres as Database Server.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Additional context**
Also would like to know the installation steps for production.

**Comment by velkymx** [comment]
ProcessMaker 4 uses Eloquent for our database layer. You can find instructions on configuring your database at https://laravel.com/docs/5.8/database
