### ISSUE TITLE
Unable to get the screen version object related to a task from API

### ISSUE THREAD

**Issue by paydaycay** [ProcessMaker/processmaker#2886]
**Is your feature request related to a problem? Please describe.**
The task API /tasks/{task_id} returns a screen version id but we have no way to retrieve a screen version object from API. So we can't process the whole workflow only by API.

**Describe the solution you'd like**
I would like an API to retrieve a screen version by its id like : 
GET /api/1.0/screen_versions/{screen_version_id}

**Comment by velkymx** [comment]
To get the correct screen version via the API you should use the request_token api end point.

**Comment by paydaycay** [comment]
I can't find any request_token api endpoint. Neither in the api documentation nor in the code directly. 

Any help please ? 

What I want is the screen version object with all items it contains.

**Comment by paydaycay** [comment]
@velkymx In fact, I already have the screen version ID but what I want is to retrieve the whole object via API. Any way to get that ?
