### ISSUE TITLE
Script Executors: Loading dynamic libraries

### ISSUE THREAD

**Issue by nolanpro** [ProcessMaker/processmaker#2887]
See https://github.com/ProcessMaker/processmaker/wiki/Customizing-Docker-Script-Executors

Allow an an admin user to build the docker executor with custom dockerfile additions
- [x] Core updates
- [x] Admin UI

Remaining items from feedback:
- [x] add "Add" executor
- [x] UI updates to scripts, allow user to choose executor
- [x] Assign default executor when creating a script and is not set (service task seeds in packages)
- [x] Update all other language packages
- [x] Fix tests
- [x] Rerecord video

Deployment steps:
- [ ] Merge PRs (listed in wiki)
- [ ] Publish existing (python, java, csharp) docker-executor-* repos to packagist
- [ ] Add new (php, node, lua) docker-executor-* repos to packagist
- [ ] Rebuild circleci after packages are published to packagist

**Comment by PMQABen** [comment]
Still trying to work with this. Found the cancel button when rebuilding an executor does not work.

**Comment by PMQABen** [comment]
At least the first two bullet points should be addressed before this is ready to continue in QA. 😄
