### ISSUE TITLE
Environment Variables with Dashes

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2908]
Create two Environment Variables:
foobar
foo-bar
Create and run the following PHP script:
#*
$foobar  = getenv('foobar');
$foobar2 = getenv('foo-bar');

return [$foobar,$foo_bar];
Result:

{
  "output": [
    "FOOBAR",
    false
  ]
}
Expected:
Able to use a dash in an EnVar name, or front/rear-end validation to restrict the usage of the dash.

**Comment by johnblackspear** [comment]
Confirmed
