### ISSUE TITLE
User Avatar Updated Wrong User

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2915]
When editing a user and update the avatar, the logged in user's avatar is being updated instead of the user being edited.

**Comment by sanjacornelius** [comment]
@velkymx  can't reproduce on lastest develop. 

<a href="https://www.loom.com/share/e75d052331e14d53a27125fc3a9cdad6"> <p>2 March, 2020 - Loom Recording - Watch Video</p> <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/e75d052331e14d53a27125fc3a9cdad6-with-play.gif"> </a>

**Comment by velkymx** [comment]
OK I'll close for now. Will reopen if issue resurfaces
