### ISSUE TITLE
Watchers that use Data Connectors fail

### ISSUE THREAD

**Issue by danloa** [ProcessMaker/processmaker#2917]
**Describe the bug**
A watcher that uses DataConnectors generates the following error in an API  response of the call http://172.16.3.125:8000/api/1.0/scripts/execution/:

`
{"exception":"ProcessMaker\\Exception\\ScriptException","message":"`cambio` Error: GET http:\/\/dummy.restapiexample.com\/api\/v1\/employees resulted in a `405` response`:\n{\n    \"message\": \"The POST method is not supported for this route. 
`

**To Reproduce**
1. Create a data connector pointing to any URL.
2. Create a Screen with a watcher that uses the data connecter created before.
3. When the watcher is executed  the response of the call
http://172.16.3.125:8000/api/1.0/scripts/execution/srn5e5d6c939e8957.37239078'
returns the described error.

**Expected behavior**
Watchers should work properly with Data Connectors

**Screenshots**
![image](https://user-images.githubusercontent.com/14875032/75716224-25b1f400-5ca5-11ea-9f42-31fb791de846.png)

**Screen json example
[screen1.json.txt](https://github.com/ProcessMaker/processmaker/files/4277835/screen1.json.txt)

**Comment by sanjacornelius** [comment]
@danloa  @velkymx Both @nolanpro and I have tried to reproduce this bug with no luck. @nolanpro  stated that there is a fix for this in `develop` and suggests reinstalling the data source package.

**Comment by danloa** [comment]
@sanjacornelius, indeed I verified that the problem is not present in the latest develop branches

**Comment by sanjacornelius** [comment]
@danloa Awesome! @velkymx closing this ticket, issue no longer present.

**Comment by PMQABen** [comment]
Nolan had to make some changes to the data sources package, once that was applied, the error no longer occurs
