### ISSUE TITLE
Timeline Decisions

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2932]
When a gateway decision is executed we should show the label on the timeline. 

Ex: 2020-04-01 Gateway: Loan 200k Approved
or
Ex: 2020-04-01 Gateway: Loan 200k Declined

For the icon show the Diamond gateway shape

**Comment by velkymx** [comment]
If the label is not configured the show: Gateway: Label Undefined

**Comment by PMQABen** [comment]
Will this work on all four types of gateways, or just certain kinds?

**Comment by PMQABen** [comment]
I'm not seeing a diamond icon.
![image](https://user-images.githubusercontent.com/28575916/77683392-8d322b00-6f55-11ea-844a-413af2c9878d.png)
