### ISSUE TITLE
Variables on Sequence Flow

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2947]
As a process designer I need to be able to set or change a variable as the result of a exclusive gateway flow evaluation. If the outbound flow is evaluated (to true) and the flow taken, then I can setup an optional variable. This feature is to simplify adding values or counters to the process data.

**Data flow:** Gateway > Flow Evaluation TRUE > Set / Update Variable > Next Task

Currently to achieve this you'd need to create a process that looks like this:

![image](https://user-images.githubusercontent.com/535300/81207032-cb256480-8f81-11ea-9ed3-dfea1d97f2da.png)

**New UI for Gateway Flow:**

![image](https://user-images.githubusercontent.com/535300/81206749-6833cd80-8f81-11ea-8660-163261e6fb28.png)

**Comment by PMQABen** [comment]
Good example process that can be used for testing:
[Var in SequenceFlow  2947.json.txt](https://github.com/ProcessMaker/processmaker/files/4383543/Var.in.SequenceFlow.2947.json.txt)

**Comment by ZLTM** [comment]
Working fine with 'Var in SequenceFlow 2947'

**Comment by velkymx** [comment]
This needs some UI refinement.

**Comment by velkymx** [comment]
![image](https://user-images.githubusercontent.com/535300/81098298-08282300-8ebe-11ea-97f5-12eb0d91feff.png)

**Comment by caleeli** [comment]
Changes required in Nayra (https://github.com/ProcessMaker/nayra/issues/173):

Add the following behavior to the FlowInterface:
```
interface FlowInterface extends EntityInterface, BpmnEventsInterface
{
    const EVENT_FLOW_ACTIVATED = 'EVENT_FLOW_ACTIVATED';

    /**
     * Register the flow events during the process building
     */
    public function registerFlowEvents();

    /**
     * Get the transition object that is triggered when
     * this flow is activated.
     *
     * @return TransitionInterface
     */
    public function getTransition();

    /**
     * Set the transition object that triggers this flow object
     *
     * @return void
     */
    public function setTransition(TransitionInterface $transition);
}
```

**Comment by caleeli** [comment]
How to store the new property:

```
<sequenceFlow
  id="node_5"
  name="index++"
  condition="index<10"
  sourceRef="gateway_1"
  targetRef="task_2"
  pm:config="{operations: [
    {
      variable: 'index',
      expression: 'index + 1'
    }
  ]}"
>
</sequenceFlow>
```
