### ISSUE TITLE
Installation issue with database setup

### ISSUE THREAD

**Issue by jemiris** [ProcessMaker/processmaker#2960]
Hi,
Here is my page view. I'm using windows 10 version and php 7.312v
![image](https://user-images.githubusercontent.com/27679841/76761863-2f178200-67b6-11ea-8eed-6ef17ebc5992.png)

**Comment by velkymx** [comment]
@jemiris Looks like you already have an .ENV file in the root of the PM4 installation. Delete that file and rerun the install command.
