### ISSUE TITLE
Safari Script Editor Broken

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2974]
![image](https://user-images.githubusercontent.com/535300/77184303-dcc3b300-6a8c-11ea-82fa-f27da9976c7f.png)

**Comment by tdondich** [comment]
For this, I think what would be beneficial is the request for preview creates a nonce that tracks the request.  In the response, the nonce is returned to the browser, which then the client listens for script task results with a nonce response that matches. Then on server side, once the preview result is done, it broadcasts on the channel with the nonce.  This ensures that the results shown are for the preview requested, even if two people are logged in with same user, or user is editing two scripts in different windows, etc.
