### ISSUE TITLE
Login "Remember Me" Not Working

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2975]
**Steps to Reproduce:**
1. Go To Log In Page
1. Check "Remember Me" and login
1. Wait for a session timeout or jsut close the browser
1. Go Back to Log in, see that Remember is not working because you need to type your credentials again.

**Current Behavior:**
The remember me checkbox is not saving the credential s as it should:

https://processmaker.gitbook.io/processmaker/using-processmaker/log-in#log-on

Optionally, select the Remember me check box to not enter your log in credentials in the future.

**Expected Behavior:**
Credentials should be kept in the login screen when "remember me" is checked

**Comment by PMQABen** [comment]
We should consider changing the "remember me" text to something that better reflects the changes here, but this does work as intended.
