### ISSUE TITLE
Notifications Not Clearing by Broadcast

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2978]
A notification of a pending task will only clear if the task is accessed through the notification itself. If instead the task is visited elsewhere (through the general to-do task list, or from the request page task list) the notification will stay alive. When clicked, it will obviously go to the Task Completed view. Task notifications when tasks are completed, regardless of whether the task was reached through the notification itself or not.

Notice the following example, I have a task assigned, to * Fill SMS Form*. You can see the latest notification and the task in the Task List: 

![image](https://user-images.githubusercontent.com/535300/77340984-493bed80-6ceb-11ea-8d67-fe8955f03d66.png)

The task was opened through the Task list, not the notification pane. So now note what happens when the task form is submitted: The next task Approve SMS is added to the task list, and a new notification added to the notification pane. However the old notification for the first task is still there, even if that task was already completed:

![image](https://user-images.githubusercontent.com/535300/77341005-51942880-6ceb-11ea-86ce-f8a57424991f.png)

**Comment by PMQABen** [comment]
Request started/canceled/completed notices do not go away, but that does not appear to have been the aim of this ticket, just task notifications.

I'm noticing something when a task is assigned to a different user. They get the new task notification, which goes away after the task is first completed, but then returns after the next page navigation or reload.

**Comment by PMQABen** [comment]
After digging further into this, the notification for a task being assigned, and a task being completed, look the same on the bell drop-down menu. That's why I was seeing the task re-appear.

The ticket as written is fixed. Closing this and moving to done.
