### ISSUE TITLE
Task Columns Not Translating

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2979]
![image](https://user-images.githubusercontent.com/535300/77343365-cae14a80-6cee-11ea-9e2b-412cbb35c102.png)

The headers should translate

**Comment by marcoAntonioNina** [comment]
![Selection_059](https://user-images.githubusercontent.com/1747025/78031105-13bd8280-7331-11ea-8692-56bc67a5bfdf.png)

error not found in develop branch, maybe it was solved with another ticket.

**Comment by PMQABen** [comment]
![image](https://user-images.githubusercontent.com/28575916/78057441-977c6c80-733b-11ea-8103-3fccae763e99.png)
It's occurring. Fresh installation of the translation package, running in Firefox.

**Comment by marcoAntonioNina** [comment]
@PMQABen this occurs in the requests and  package save search
