### ISSUE TITLE
Allow specifying shared memory size for docker image configuration

### ISSUE THREAD

**Issue by tdondich** [ProcessMaker/processmaker#2982]
**Is your feature request related to a problem? Please describe.**
Some docker images which will be used by script tasks may require additional shared memory by host in order to execute. Example is the selenium docker images need the --shm-size=2g flag passed in order for memory consumption to be allowed.

**Describe the solution you'd like**
We need configuration for docker images to allow specifying a shared memory size. This should be done via configuration file or registration.

**Describe alternatives you've considered**
none

**Additional context**
https://github.com/SeleniumHQ/docker-selenium#running-the-images

**Comment by velkymx** [comment]
@nolanpro while you're in the docker stuff. Please add a flag for this in the ENV file and a default value of 256m as part of the installer.

**Comment by nolanpro** [comment]
@velkymx Yeah I'll take a look
