### ISSUE TITLE
Avatar Broken Image

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2984]
1. Create a new user
1. Edit user
1. Upload an avatar image
1. Go to any vuetable

![image](https://user-images.githubusercontent.com/535300/77438045-975ff800-6da2-11ea-8778-7950d8b85401.png)

We need to figure out if it is a server permission issue or the image being referenced incorrectly.

**Comment by danloa** [comment]
I can't reproduce it. Tested locally with the latest develop branch and in QA server https://develop.spark.qa.processmaker.net (version ProcessMaker 4 v 4.0.3) and it worked fine. 

Attached a gif showing how it worked saving the user and after without using the save button.

![bug2984](https://user-images.githubusercontent.com/14875032/77549657-7bce1d80-6e86-11ea-84d4-18a74c0a9a79.gif)
