### ISSUE TITLE
Modal Close Buttons Hidden

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#2991]
![image](https://user-images.githubusercontent.com/535300/77575154-5c3bf280-6e90-11ea-8889-d04e793db531.png)

Please confirm all modals work.

**Comment by PMQABen** [comment]
No code has been committed, close buttons still missing, not ready for QA.

**Comment by PMQABen** [comment]
Modal close buttons are still missing on the latest develop build.

**Comment by velkymx** [comment]
This is only affecting the Screen Builder modals. That's the key.
