### ISSUE TITLE
Calculated Fields generate infinite loop

### ISSUE THREAD

**Issue by danloa** [ProcessMaker/processmaker#3008]
**Description:**
If a screen has a calculated field that returns a date it generates an infinite loop.

**To Reproduce**
1. Create a Screen and a Process that uses the screen.
2. Add a calculated field that uses JavaScript and returns: **return new Date();**
3. Crete a case and in the first task that uses the screen  an error will be displayed in the console.

![image](https://user-images.githubusercontent.com/14875032/78180798-4ea6df80-7431-11ea-99f3-39d9630a97a7.png)

**Additional context**
return new Array; or return 1; works fine, it seems that the error happens just with dates.

The attached process has an example:

[Test Process.json.txt](https://github.com/ProcessMaker/processmaker/files/4417304/Test.Process.json.txt)

**Comment by danloa** [comment]
@velkymx 

The problem is in the screen builder. It is caused because we update the transientData, and this update  triggers the computed property and it evaluates again the expression _return new Date()_ and by milliseconds the expression has changed, so the transientData is updated again and so on.

The workarround is to use an string that doesn't change in millisecods, like:

**return (new Date()).toISOString().slice(0,10);**

**Comment by tdondich** [comment]
@danloa thats a hacky solution.  If the update is right before the change of a second then itll trigger it again.  This isnt the right way to do it.  Yoi should keep an update map to keep track of updated properties and if the property has been touched then dont update it again.  I politely request we reject the proposed solution.

**Comment by danloa** [comment]
@tdondich Yes it was a hacky workaround. The problem with the current implementation of calculated fields and watchers is that we are observing changes in an object "transientData" and the changes come from everywhere and they can pop up at any moment. We are planning to do a complete overhaul of all this.

My proposed solution for this the 4.0.6 version of ProcessMaker is in this PR:

https://github.com/ProcessMaker/screen-builder/pull/751

The idea is to have a "debounce" for calculated fields (< 100ms). If they are updating too fast, like when we are returning a new Date(), we wait until the 100ms passes. That way the infinite loop is cut.

**Comment by tdondich** [comment]
The debounce is also a hacky solution.  Are we blocked with this or can we take another day or so to rethink it?

**Comment by velkymx** [comment]
We're reworking the entire data event model into a new component (David is working on it) this is a stop gap until we switch over. @tdondich

**Comment by PaolaPellegrini** [comment]
The first time I save the configuration with java Script, I get an error in console.
Verified at https://develop.spark.qa.processmaker.net/

![Issue3008Rejected1](https://user-images.githubusercontent.com/51709910/83833788-bf30dd80-a6ba-11ea-86f5-79b9eff44f60.png)

Rejected!

**Comment by danloa** [comment]
@PaolaPellegrini  @PMQABen  Can you attach the screen that generated the error? In https://develop.spark.qa.processmaker.net/ there aren't screens. I created one and it worked fine.

**Comment by PaolaPellegrini** [comment]
in the last build the error is no longer replicated.
