### ISSUE TITLE
Processmaker 4.0.3 - Gateway conditions array

### ISSUE THREAD

**Issue by roasten** [ProcessMaker/processmaker#3013]
**Describe the bug**
In the design Im using a checkbox group with multiple selection meaning the variable will result in an array.
When using the array variable in condition as
variable in ["option"] it doesn't work, meaning not matching the result value.

The array list is with string values, as example "dog".
variable in ["dog"]

Do I do anything wrong? The condition variable is ok, since no warning of false variable name.
According to the process_request_tokens.data field I have variable of the array with correct value.

**Comment by roasten** [comment]
So after some deeper review the ExpressionLanguage seems not to support array as variable to validate. In my example the variable is an array. By doing variable[0] == "dog" Im getting boolean true, but there is no chance to track what content is index value 0, as an example. In previous version of Processmaker you supported in_array(), in Processmaker 4, how do I do the same validation?

**Comment by velkymx** [comment]
Have you tried the array methods provided?

https://symfony.com/doc/current/components/expression_language/syntax.html
