### ISSUE TITLE
ProcessMaker 4 installation not working

### ISSUE THREAD

**Issue by khoerrizal52** [ProcessMaker/processmaker#3026]
**Describe the bug**
I use branch release/4.0.3 and follow installation instruction in code description. After do `npm install`, i got error shown below.
`npm WARN @processmaker/modeler@0.18.5 requires a peer of @processmaker/screen-builder@0.21.5 but none is installed. You must install peer dependencies yourself.
npm WARN @processmaker/modeler@0.18.5 requires a peer of @processmaker/vue-form-elements@0.13.2 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})`

If i ignore that message, i got another error after do `vagrant ssh` and then do `php artisan processmaker:install`, i got another message error.
`Could not open input file: artisan`

**To Reproduce**
1. Clone the git in local laptop.
2. Change branch to release/4.0.3
`git checkout release/4.0.3`
3. Run `composer install`.
4. Run `npm install`.
5. Run `vagrant up`.
6. Run `vagrant ssh`.
6. Run `php artisan processmaker:install`

**Expected behavior**
ProcessMaker 4 run properly in local server.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - node: 12.14.1
 - npm: 6.14.4
 - vagrant: 2.0.2

**Comment by velkymx** [comment]
@khoerrizal52 If you are running into NPM issues, I recommend you grab the release TAR file and then you don't have to run NPM. Just unzip and use. 

https://github.com/ProcessMaker/processmaker/releases

As for the issue with vagrant. You need to make sure you follow the installation directions in the README. It seems you're missing the folder configuration as well as you are having some npm configuration issues.
