### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by nolanpro** [ProcessMaker/processmaker#3031]
Issue/branch to keep track of translation updates in core and packages for 4.0.4
- [x] Add core translations to this branch feature/3031
- [x] Add any package translations
- [x] Submit core/package translations to smartling
- [x] Download core and package translations from smartling and add to translations package

**Comment by PMQABen** [comment]
[Here's a list of all open JIRA requests for missing/incorrect translation strings](https://processmaker.atlassian.net/issues/?jql=issuetype%20in%20(Bug%2C%20Task)%20AND%20component%20%3D%20%22Package%3A%20Translations%22%20AND%20project%20%3D%20FOUR%20AND%20status%20in%20(%22In%20Backlog%22%2C%20Research%2C%20Scheduled%2C%20Triage))

**Comment by PMQABen** [comment]
Column headers in `/designer/screens` are not translating, any language. Occurs when reloading the page.
![image](https://user-images.githubusercontent.com/28575916/79369484-e1ea1580-7f05-11ea-9758-47186cbcf93f.png)

Likely unrelated to this, since the commits are just JSON updates.

**Comment by PMQABen** [comment]
These issues are either going to be solved with the next package update, or with fixes to core PM4.
