### ISSUE TITLE
Npm install failed

### ISSUE THREAD

**Issue by lfranz** [ProcessMaker/processmaker#3053]
**Impossible to complete npm installation dependencies**
I'm trying to install Processmaker but npm install command fail with this errors:

```
npm WARN tarball tarball data for monaco-editor@0.19.3 (sha512-2n1vJBVQF2Hhi7+r1mMeYsmlf18hjVb6E0v5SoMZyb4aeOmYPKun+CE3gYpiNA1KEvtSdaDHFBqH9d7Wd9vREg==) seems to be corrupted. Trying one more time.
npm WARN tar ENOENT: no such file or directory, lstat '/var/www/html/node_modules/.staging/monaco-editor-7f525680/esm/vs/base'
[...]
npm ERR! code EINTEGRITY
[...]
npm ERR! Verification failed while extracting monaco-editor@0.19.3:
npm ERR! sha512-2n1vJBVQF2Hhi7+r1mMeYsmlf18hjVb6E0v5SoMZyb4aeOmYPKun+CE3gYpiNA1KEvtSdaDHFBqH9d7Wd9vREg== integrity checksum failed when using sha512: wanted sha512-2n1vJBVQF2Hhi7+r1mMeYsmlf18hjVb6E0v5SoMZyb4aeOmYPKun+CE3gYpiNA1KEvtSdaDHFBqH9d7Wd9vREg== but got sha512-L95YyFGTDg4jV6LjQx6APkZzHYlyu3Vj+TwWEP5WfCkVduACi2XowE8xy3GYMJ5lyse/bNBaQEvIdtICbQMGeg==. (5519750 bytes)
[...]
```

**Software info**
 - OS: Debian 10
 - Node: v10.20.1
 - Npm: 6.14.4
 - Php: 7.3.16 (cli)

**Comment by velkymx** [comment]
@lfranz this looks like an issue with NPM missing folders. 

Note `no such file or directory` seems to be the source.

**Comment by lfranz** [comment]
Yes, i think that 'no such file or directory' is caused by 'npm WARN tarball tarball data for monaco-editor@0.19.3 seems to be corrupted. Trying one more time.'
All files on my installation are the same of the github repository.
