### ISSUE TITLE
Bug changing the screen property

### ISSUE THREAD

**Issue by caleeli** [ProcessMaker/processmaker#3054]
**Bug changing the screen property**
Looks like this issue is related to VueMultiselect and VueFormRenderer

**To Reproduce**
![vue-multiselect-form-renderer](https://user-images.githubusercontent.com/8028650/79160827-72124880-7da8-11ea-9e97-16046d024ffe.gif)
1. Create a form task
2. Set a screen for the task (screen 1)
3. Choose a different element (like the process)
4. Choose again the form task
5. Change the screen to another one (screen 2)
6. Change the screen back to the previously selected (screen 1)
7. Choose a different element (like the process)
8. Choose again the form task
9. The selected screen is the 2nd screen, but it should be the 1st one (screen 1)

**Expected behavior**
The selected screen is the 2nd screen, but it should be the 1st one (screen 1)

**Comment by velkymx** [comment]
This is resolved
