### ISSUE TITLE
Empty SignalRef causes an HTTP 500 on Process PUT

### ISSUE THREAD

**Issue by johnblackspear** [ProcessMaker/processmaker#3058]
**Describe the bug**
Attempts to save a diagram with an unconfigured Signal Event results in an HTTP 500 error from the API.

**To Reproduce**

1. Create a new process.
2. Add any Signal Event.
3. Leave the Signal Selector empty (do not further configure the Signal Event)
4. Click save

**Expected behavior**
Either:

1) The Process model can handle saving of processes with Signal Events that do not have a signal reference set.
2) We have the BPMN validator reporting that SignalRefs are required. This might need to be done anyway but probably in a separate ticket.

**Screenshots**

HTTP 500 on save with no warnings in validator:
<img src="https://user-images.githubusercontent.com/28595383/79388462-e68de880-7f5c-11ea-8abd-d584ee54923d.png"/>

**Additional Context**

Error occurs in the `Process` model, stack trace snippet:
```
Undefined index: signalRef at /home/vagrant/processmaker/ProcessMaker/Models/Process.php:1110)
```

**Comment by velkymx** [comment]
Add validation to the Signal Select
