### ISSUE TITLE
Allow configurable storage path

### ISSUE THREAD

**Issue by nolanpro** [ProcessMaker/processmaker#3063]
Devops has been manually copying release files from the zipped release in github. This creates problems such as the one where DataSourcesController was deleted from the repo but left on the server, causing script executor builds to crash.

A solution would be to unzip to an empty folder for each time we need to deploy (then symlink to that folder after install steps are completed)

The problem with doing this is that the user's files are stored in the 'storage/app' inside the repo but need to persist across releases.

To fix this I suggest making Laravel's storage_path configurable with a env var

See: https://stackoverflow.com/a/40139696/176751

Then point to a folder outside the release folder that persists files if the APP_STORAGE env var is set

With that set up, a deploy process might look like this:

1. Download/unzip release from github into its own folder, like releases/v4.0.4
1. Copy or rebuild the .env from the previous version, making sure it includes something like APP_STORAGE='../app-storage' and has any new vars set in .env.example
1. Do the usual composer install, composer require packages, php artisan package install commands, npm etc.
1. Once the new version is all setup and configured, change the symlink (that nginx is pointing to) to the release folder.

**Comment by velkymx** [comment]
This is integrated
