### ISSUE TITLE
Script Executors Cannot be Changed

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#3076]
Once a script task is configured you should not be allowed to change the script executor to a different language, but I should be able to change between the different dockers with the same language. Current config page isn't loading the form defaults.

![image](https://user-images.githubusercontent.com/535300/80518124-ea494400-893a-11ea-92f6-6a7754f45dd6.png)

**Comment by nolanpro** [comment]
Fixed in https://github.com/ProcessMaker/processmaker/issues/3130
