### ISSUE TITLE
User Permissions Errors

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#3078]
![image](https://user-images.githubusercontent.com/535300/80625807-930ea680-8a02-11ea-8919-ea77b1102174.png)

Clicking to expand any of the permissions boxes results in nothing happening and this JS error: 

![image](https://user-images.githubusercontent.com/535300/80625866-a4f04980-8a02-11ea-98b8-961b3a7da11d.png)

**Comment by velkymx** [comment]
Also happens in Groups.
admin/groups/2/edit

**Comment by danloa** [comment]
@velkymx  this issue can't be reproduced. It is possible that the issue was related to a JQuery upgrade that already has been reverted.
