### ISSUE TITLE
Docker Image Readme

### ISSUE THREAD

**Issue by eldw** [ProcessMaker/processmaker#3081]
Hi Guys,
 
I'm new here but happy to see a vivid community.

I tried to have Procerssmaker installed with a docker Image. I found a version 4.0.1 here: https://hub.docker.com/r/processmaker/processmaker

Looks all good, but I get stuck when I'm asked for the DB settings after the deployment (setp 4/5).

![grafik](https://user-images.githubusercontent.com/49850577/80980532-03fdf600-8e29-11ea-95cc-2fa158afdfc6.png)

I may have made a mistake because it should all come with the docker-compose. Actually the db (mysql) is included there 

> # mysql
> RUN yum localinstall -y https://repo.mysql.com//mysql57-community-release-el7-11.noarch.rpm
> RUN yum install -y mysql-community-server

However it would be nice to have a docker image with readme and FAQ so I can help myself to get it all up and running. A docker image of the most recent version would also be appreciated. 

I considered to have ProcessMaker installed with the binaries here, but my server is just designed to have webapps running in containers (docker files) as I think this is the way to move forward. 

I could now build my own dockerfile but I think somebody may have done it already and I would be lucky to jump on the train and have a pleasant ride.

Thanks
D.

**Comment by velkymx** [comment]
@eldw I recommend posting over on the PM3 forum. ProcessMaker 4 is not related to that product. https://stackoverflow.com/questions/tagged/processmaker
