### ISSUE TITLE
Assignment by Rules Broken

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#3090]
When using the task assignment by expression the process throws an error.

The configuation:

![image](https://user-images.githubusercontent.com/535300/81092351-5258d680-8eb5-11ea-83d7-356f5f117ae2.png)

The task detail:

![image](https://user-images.githubusercontent.com/535300/81092402-643a7980-8eb5-11ea-9df5-13d420af5814.png)

Process is attached

[Assignment Rules 2.json.txt](https://github.com/ProcessMaker/processmaker/files/4582255/Assignment.Rules.2.json.txt)

**Comment by PMQABen** [comment]
@danloa 
Using the process attached, when the "assignedGroup" variables are properly inserted into the process it will assign the second task correctly.

However, if I run the process and on the first task I submit either a blank "assignedGroup" variable, or give it a number that has not been defined, the task does not throw an error. When this happens, it defaults to assigning the task to the previous assignee.

I'm not sure if this is intended behavior or not.
