### ISSUE TITLE
Parallel Script Tasks overwrite unchanged data

### ISSUE THREAD

**Issue by caleeli** [ProcessMaker/processmaker#3092]
**Parallel Script Tasks overwrite unchanged data**

When two or more script tasks run at the same time, they could overwrite unchanged data. For example:

![image](https://user-images.githubusercontent.com/8028650/81109107-995fbf80-8ee7-11ea-96d4-b52e6569eb71.png)

The `Script 2` will overwrite (remove) the variable `a` stored by the `Script 1`

**Steps to reproduce:**

Create a process like this:
![image](https://user-images.githubusercontent.com/8028650/81108799-26564900-8ee7-11ea-8785-a9f4fc00daf6.png)
The `Sleep` task and `test_index++` task should run `test_count` times

**Comment by PMQABen** [comment]
Had Eamonn help me out with this one for testing. Ran a self-contained process on both the latest develop branch, and an older branch from a few weeks ago. The process should only run a maximum of seven times by incrementing a variable and then stop.

When run on the old branch, it would go past 7 loops loops before it stopped, and when run on the develop branch it stopped at 7 runs each time.
