### ISSUE TITLE
Importing Screens: Buttons

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#3096]
ProcessMaker Screens that exist before being upgraded to PM 4.0.3 do not show the new "Type Button" setting. Interestingly, the "Duplicate Control" feature does work correctly in pre-existing Screens.

If a new Submit Button control is added to a Screen in PM 4.0.3, then the Type Button setting is available.

FIX: 

Buttons that are missing the new configuration should import and be updated automatically with the new settings, with the default being SUBMIT.

**Comment by PMQABen** [comment]
Simple form screen with a single button, made prior to 4.0.3: [click_button.json.zip](https://github.com/ProcessMaker/processmaker/files/4583512/click_button.json.zip)

**Comment by velkymx** [comment]
This is resolved.
