### ISSUE TITLE
About Page Erroring Out

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#3098]
When in production mode and visiting the route /about you see the error page: 

![image](https://user-images.githubusercontent.com/535300/81207826-0bd1ad80-8f83-11ea-809f-93b7608a27fa.png)

**Comment by sanjacornelius** [comment]
@velkymx  No changes are needed for this issue, it was solely an issue on the staging server. The issue was due to the staging server not having a `composer.json` file.
