### ISSUE TITLE
Error build vue - precompiled css

### ISSUE THREAD

**Issue by ducdm87** [ProcessMaker/processmaker#3103]
**Describe the bug**
I ran the installation as instructed.
to build vue step. I have the following error
Module build failed:
@import '../../public/css/precompiled/bootstrap/bootstrap.scss';

**Screenshots**
![Screenshot_3](https://user-images.githubusercontent.com/2037787/81258693-77d61380-9060-11ea-8e85-7ae1e780058a.png)

Please help me solve this error!
Thank you

**Comment by velkymx** [comment]
Try running these commands:

This one will clear your node_modules and get all components fresh

```
npm ci
```

Then run the build using the npm command
```
npm run dev
```

**Comment by velkymx** [comment]
Also make sure the server folder permissions are correctly configured. The folder should be owned by the same user as the webserver (ex nginx, www, etc)
