### ISSUE TITLE
Docker Executor Creation 

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#3129]
When trying to add a new executor the screen throws an error and then i cannot set the language.

![image](https://user-images.githubusercontent.com/535300/81957696-d439b580-95c1-11ea-9e82-33f856c06a12.png)

API end point throwing 500: https://staging-pm4.processmaker.net/api/1.0/script-executors/available-languages

![image](https://user-images.githubusercontent.com/535300/81957636-b704e700-95c1-11ea-9453-d842a8a9ab24.png)

**Comment by PMQABen** [comment]
This is still throwing 500 errors.
