### ISSUE TITLE
User with view all requests permission unable to view all requests

### ISSUE THREAD

**Issue by nolanpro** [ProcessMaker/processmaker#3133]
- As an admin, create a new user. Assign "View All Requests" to the user
- Have some completed requests you can see as an admin
- Log in as the new user

Actual: No requests
Expected: Shows requests

Note: Maybe `scopeRequestsThatUserCan` in ProcessMaker/Models/ProcessRequest.php should check for that permission

**Comment by velkymx** [comment]
This has been resolved
