### ISSUE TITLE
Production installation 

### ISSUE THREAD

**Issue by chau-huu** [ProcessMaker/processmaker#3135]
Hi
After Downloading the TAR file in the release notes. and decompressed the file on your web server and then used the composer's commands to install the basic libraries. Then, the ProcessMaker 4 application will be available if you point your web server to the public directory.
I connect well to the application yet I encounter the following error:
"Sorry! API failed to load
Something went wrong. Try refreshing the application."

Thank you

**Comment by velkymx** [comment]
@chau-huu sorry you're having an issue! What do your laravel logs say? You can find them in the storage/logs directory

**Comment by chau-huu** [comment]
hi 
Here what i ve done
download the TAR file
Untar in /var/www/html/
mv porcessmaker4.0.4 processmaker
chown -R www-data: processmaker
cd processmaker 
composer install 
create user homestead in mysql
with user homestead  create a database processmaker
php artisan processmaker:install

everything seems  correct 

ProcessMaker Installer
This application installs a new version of ProcessMaker.
You must have your database credentials available in order to continue.

 Are you ready to begin? (yes/no) [no]:
 > yes

Dependencies Check
+---------------------+------------------+
| CType Extension     | 7.3.14-1~deb10u1 |
| GD Extension        | 7.3.14-1~deb10u1 |
| JSON Extension      | 1.7.0            |
| mbstring Extension  | 7.3.14-1~deb10u1 |
| OpenSSL Extension   | 7.3.14-1~deb10u1 |
| PDO Extension       | 7.3.14-1~deb10u1 |
| PDO MySQL Extension | 7.3.14-1~deb10u1 |
| PHP Version         | 7.3.14-1~deb10u1 |
| Tokenizer Extension | 7.3.14-1~deb10u1 |
| XML Extension       | 7.3.14-1~deb10u1 |
| ZIP Extension       | 1.15.4           |
+---------------------+------------------+
ProcessMaker requires a MySQL database.
 Enter your MySQL host [127.0.0.1]:
 Enter your MySQL port (usually 3306) [3306]:
 Enter your MySQL database name [processmaker]:
 Enter your MySQL username:
homestead
 Enter your MySQL password (input hidden):
ProcessMaker requires a DATA database.
 Would you like to setup different credentials or use the same ProcessMaker
connection?:
  [0] different
  [1] same
  1

 What is the URL of this ProcessMaker installation? (Ex: https://processmaker.example.com, with no trailing slash):
 https://processmaker4.sosve.local

 Would you like to enable Telescope debugging? (yes/no) [no]:
Installing ProcessMaker database, OAuth SSL keys and configuration file.
Configuration cache cleared!
Configuration cached successfully!
Configuration cache cleared!
Application cache cleared!
 Enter the desired admin username [admin]:
 Enter the email address of the admin user:
Enter the desired admin password:
 Confirm the admin password:
Enter the first name of the admin user [Admin]
 Enter the last name of the admin user [User]:>
Installing database...
ProcessMaker database installed successfully.
Encryption keys generated successfully.
Personal access client created successfully.
Client ID: 4
Client secret: 
Password grant client created successfully.
Client ID: 5
Client secret: 
The [public/storage] directory has been linked.
Copied Directory [/vendor/laravel/telescope/public] To [/public/vendor/telescope]
Publishing complete.
Installing the php script executor
Installing the lua script executor
Installing the node script executor
ProcessMaker installation is complete. Please visit the URL in your browser to continue.
Installer completed. Consult ProcessMaker documentation on how to configure email, jobs and notifications.

I the laravel log i have 

Unable to register gates. Either no database connection or no permissions table exists.
So it 's a database error but with one ? 
Thanks

**Comment by velkymx** [comment]
Look in the .env file for the database settings. Make sure they're correct. 

I recommend you run the site using Vagrant over homestead.

**Comment by bcando** [comment]
@chau-huu, I am encountering the same issue.  Did you manage to get it working without resorting to using Vagrant?

**Comment by chau-huu** [comment]
@bcando no i don't try to use Vagrant, i continue to use processmaker 3.3.
And i will wait to have a production guide installation

**Comment by JackWangz** [comment]
Hi
I got same error 
**"Sorry! API failed to load Something went wrong. Try refreshing the application"**
when I logged into the page with v4.0.8.

Any thoughts on this?
