### ISSUE TITLE
Package Command-line Test

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#3153]
DevOps would like a way to easily run an artisan command that will check that a package is installed correctly.

I'd like to add these tests to a single package.

**Actions by Email to start**

Verify: 

Permissions
Assets
Configs

**Comment by PMQABen** [comment]
This looks like a ticket that will need to be tested and vetted by DevOps, QA won't be able to assist much at all.

**Comment by PMQABen** [comment]
Installed the AbE package on a local VM, verified the IMAP variables were configured in the .env file. Edited the variables to remove the "`I`" (ex. `IMAP_INTERVAL => MAP_INTERVAL`), saved and ran the check:
```
vagrant@processmaker:~/processmaker$ art processmaker:check package-actions-by-email
ls: cannot access '/home/vagrant/processmaker/public/vendor/processmaker/connectors/actions-by-email': No such file or directory

   InvalidArgumentException  : Argument 3 passed to PhpImap\Imap::open must be a string, boolean given!
```

**Comment by nolanpro** [comment]
@PMQABen what specific IMAP_* settings did you change? I wasn't able to reproduce. If I give the wrong value, I get the "Couldn't open stream" and I think that's the desired behavior as long as it throws an error. If I set it back to the correct value I get the expected "Package installed and configured correctly"

**Comment by PMQABen** [comment]
I did a fresh pull and build of PM4 and the AbE package on my local VM, and it all seems to work as expected. The errors I saw earlier no longer occur.
