### ISSUE TITLE
Importing incorrect forms and scripts assignments

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#3154]
I exported the process called C19- Initial Report from https://c19report.cloud.processmaker.net/modeler/ and imported it into https://staging-pm4.processmaker.net/modeler/

It imported with incorrect forms and incorrect scripts.  Instead of the form COVID Symptoms - Registration NoTCs in the Webentry, it had the form LoA Manager - Rejection.  This form was not even part of the process.  It is from a completely different processes.  

The SMS imported with the wrong SMS as well.

**Comment by PMQABen** [comment]
**QA Note:** This will require creating a process that uses Web Entry and Send Email.

**Comment by ZLTM** [comment]
The process is not importing the update collection data script
![image](https://user-images.githubusercontent.com/7957742/84076437-b8001d00-a9a3-11ea-83ae-a486b116ccb0.png)
tested with c9 
https://www.dropbox.com/s/rp7f0vy30xhqyqq/C19%20-%20Condicion%20de%20Salud.json?dl=0

**Comment by ryancooley** [comment]
@ZLTM From where exactly did you export the process? The BPMN included does not include the script reference so it would not be possible to import it.

**Comment by ZLTM** [comment]
The c9 process seems to have been incomplete to begin with, I'm changing the state to solved, sorry for the inconvenience
