### ISSUE TITLE
Auth Client Pagination Missing

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#3159]
Route: /admin/auth-clients

Need to add the proper vue-table with pagination and filtering.

**Comment by PaolaPellegrini** [comment]
The solution has been verified, it does not meet the quality criteria.

See the video https://drive.google.com/file/d/1Fx2XupqLKF2vWVoGYN1dz26P9zX8-KPB/view?usp=sharing

The  solution is Rejected

**Comment by PMQABen** [comment]
Nobody can view the video. What does not meet criteria?

**Comment by PaolaPellegrini** [comment]
**Steps to Reproduce**
1. Have many Auth clients created
2. Click on the next page
3. Change the page to 25

https://drive.google.com/file/d/1E8D-13CkZS7j1SxahPYJOjlmWV5nqH0t/view?usp=sharing

As we see in the attached video, when I change the page on the second page it shows me the whole list.
It should show only the selected quantity.

Rejected!
