### ISSUE TITLE
Implement hooks for the Dynamic UI package

### ISSUE THREAD

**Issue by danloa** [ProcessMaker/processmaker#3163]
The Dynamic UI package needs to modify the behavior of PM in the following points:
- Allow to replace the Top Menu
- Home page redirect 
- Allow to conifgure the top menu and the home page in User Edit and User Groups forms

**Comment by ZLTM** [comment]
We have problems changing the menu using groups
https://processmaker.atlassian.net/browse/FOUR-1570

**Comment by ZLTM** [comment]
Working on release-testing
