### ISSUE TITLE
Google Places Failing

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#3189]
When we go to screen, google places it shows (You already started the loading of google maps)

![image](https://user-images.githubusercontent.com/535300/84192182-7a0c0300-aa4e-11ea-8529-4ebdc7bd5417.png)

And then it block showing another error (Oops! Something went wrong)

![image](https://user-images.githubusercontent.com/535300/84192198-8001e400-aa4e-11ea-8e66-fe775b328572.png)

**Comment by PMQABen** [comment]
When there is no Google API token in environment variables, the error being thrown is a generic 404 banner error as opposed to the newly added error banner `Cannot load Google Maps API Token`

**Comment by PMQABen** [comment]
Finished testing locally, this will be good to go when all the PRs are merged and built.
