### ISSUE TITLE
php artisan processmaker:install - >The maximum column size is 767 bytes

### ISSUE THREAD

**Issue by jemiris** [ProcessMaker/processmaker#3197]
**Describe the bug**

While installing the `php artisan processmaker:install` some of the tables are not migrated

**To Reproduce**

1. Go to 'Installation of processmkaer 4' `php artisan processmaker:install `. I'm using php 7.3 and windows 10pro. In windows 10 there is not vagrant i have used instead i have used virtual host.
2. See error

**Screenshots**

![screen 1](https://user-images.githubusercontent.com/27679841/84514287-64b20580-ace8-11ea-879d-df672cdf2f37.PNG)

![screen 2](https://user-images.githubusercontent.com/27679841/84514300-6bd91380-ace8-11ea-8217-fbde720ac488.PNG)

**Desktop (please complete the following information):**
 - OS: [Windows 10 pro]
 - php Version [ PHP 7.3.12 ]
- node [ v12.16.1 ]
- I'm not using vagrant instead i use virtual host

**Comment by jemiris** [comment]
1.  I have fixed this issue by adding below code in **conig/database.php**

`'connections' => [
        'processmaker' => [
            
            'charset' => 'utf8',  // Just change the to utf8
             'collation' => 'utf8_general_ci'  // Just change the to utf8_general_ci
        ]
`
2. And run the **php artisan config:cache**
3. Then run the ** php artisan processmaker:install**

**Comment by velkymx** [comment]
Make sure you are running either MySQL 5.7 or MariaDB 10.*
