### ISSUE TITLE
Install Fails

### ISSUE THREAD

**Issue by shahind** [ProcessMaker/processmaker#3204]
Trying to install processmaker 4.0.5 in wamp, I face many problem:

1- npm install Fails with this error:

> @processmaker/processmaker@4.0.4 postinstall C:\wamp64\www\process
> `mkdir -p public/css/precompiled && cp -rf node_modules/npm-font-open-sans public/css/precompiled/npm-font-open-sans && cp -rf node_modules/bootstrap/scss public/css/precompiled/bootstrap && cp -rf node_modules/@fortawesome/fontawesome-free public/css/precompiled/fontawesome-free && cp -rf node_modules/vue-multiselect/dist/vue-multiselect.min.css public/css/precompiled`
>
>The syntax of the command is incorrect.
>npm ERR! code ELIFECYCLE
>npm ERR! errno 1
>npm ERR! @processmaker/processmaker@4.0.4 postinstall: `mkdir -p public/css/precompiled && cp -rf node_modules/npm-font-open-sans public/css/precompiled/npm-font-open-sans && cp -rf node_modules/bootstrap/scss public/css/precompiled/bootstrap && cp -rf node_modules/@fortawesome/fontawesome-free public/css/precompiled/fontawesome-free && cp -rf node_modules/vue-multiselect/dist/vue-multiselect.min.css public/css/precompiled`
>npm ERR! Exit status 1
>npm ERR!
>npm ERR! Failed at the @processmaker/processmaker@4.0.4 postinstall script.
>npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

I fixed this error by skipping scripts which I think is not an appropriate solution.

2- php artisan processmaker:install Fails, it asks a question and answers automatically no, actually confirm() function not works properly,
![image](https://user-images.githubusercontent.com/10776307/84839872-48e59100-b053-11ea-911f-bd9badb63c32.png)

I tried both cmd and Cygwin terminal

**Comment by shahind** [comment]
I even tried to modify install file from ProcessMaker/Console/Commands/install.php and setting database info manually, but even in this case MigrateFresh not works and nothing is create in DB and I get `there is no user table` errors when it tries to create admin user

**Comment by jemiris** [comment]
Hi @shahind ,

1.  I have got the same issue. I just run the command `mkdir -p public/css/precompiled && cp -rf node_modules/npm-font-open-sans public/css/precompiled/npm-font-open-sans && cp -rf node_modules/bootstrap/scss public/css/precompiled/bootstrap && cp -rf node_modules/@fortawesome/fontawesome-free public/css/precompiled/fontawesome-free && cp -rf node_modules/vue-multiselect/dist/vue-multiselect.min.css public/css/precompiled`

2.  Next, I just run the `npm run dev`. It works well for me. Give a try it may help someone.
