### ISSUE TITLE
ErrorException : mtempnam(): file created in the system's temporary directory

### ISSUE THREAD

**Issue by jemiris** [ProcessMaker/processmaker#3205]
**Describe the bug**

While installing the `php artisan processmaker:install` some of the tables are migrated. After that there is an issue

**To Reproduce**

1. Go to 'Installation of processmkaer 4' `php artisan processmaker:install `. I'm using php 7.3 and windows 10pro. In windows 10 there is not vagrant i have used instead i have used virtual host.
2. See error

**Screenshots**

![screen 3](https://user-images.githubusercontent.com/27679841/84898701-4c196500-b0c5-11ea-8414-1b4b86c6d216.PNG)
![screen 5](https://user-images.githubusercontent.com/27679841/85137050-355a4600-b25e-11ea-8625-da4c8c54e833.PNG)

**Desktop (please complete the following information):**
 - OS: [Windows 10 pro]
 - php Version [ PHP 7.3.12 ]
- node [ v12.16.1 ]
- I'm not using vagrant instead i use virtual host

**Comment by velkymx** [comment]
We don't support installing on Windows 10 pro. If you're not going to use vagrant I suggest you use a virtual machine with linux to install on.

**Comment by jemiris** [comment]
Yes I would try virtual machine running Linux for your installation

Thanks

**Comment by velkymx** [comment]
Also make sure you are running either MySQL 5.7 or MariaDB 10.*
