### ISSUE TITLE
Running docker-executor-lua:install - Error response from daemon: Cannot kill container: generator: Container

### ISSUE THREAD

**Issue by jemiris** [ProcessMaker/processmaker#3207]
**Describe the bug**

While installing the `php artisan processmaker:install` the tables are migrated. After that, there is an issue

**To Reproduce**

1. Go to 'Installation of processmkaer 4' `php artisan processmaker:install `. I'm using php 7.3 and windows 10pro. In windows 10 there is not vagrant I have used instead I have used virtual host.
2. See error

**Screenshots**

![screen 4](https://user-images.githubusercontent.com/27679841/85019198-0ffd0780-b18c-11ea-9eaf-09692e0b015c.PNG)

**Desktop (please complete the following information):**
 - OS: [Windows 10 pro]
 - php Version [ PHP 7.3.12 ]
- node [ v12.16.1 ]
- I'm not using vagrant instead i use virtual host

**Comment by velkymx** [comment]
Do you have docker installed? How are you managing your php / node installation? Are you using the linux sub system on Windows?

**Comment by jemiris** [comment]
Yes, I have installed docker latest version Docker version 19.03.8,


The way I have followed for other laravel projects to run the projects

1. I would add the project folder location, add the server name with host

`C:\wamp64\bin\apache\apache2.4.41\conf\extra\httpd-vhosts.conf
`
```
<VirtualHost *:80>
  ServerName smlocal.com
  ServerAlias smlocal.com
  DocumentRoot "${INSTALL_DIR}/www/sampleProject/public"
  <Directory "${INSTALL_DIR}/www/sampleProject/public">
    Options +Indexes +Includes +FollowSymLinks +MultiViews
    AllowOverride All
    Require local
  </Directory>
</VirtualHost>
```

2. Then I would add the host in this location file C:\Windows\System32\drivers\etc\hosts

`127.0.0.1 smlocal.com`

**Comment by velkymx** [comment]
Update to the latest version.
