### ISSUE TITLE
Developer Beta Processmaker Server : Process not downloaded

### ISSUE THREAD

**Issue by jemiris** [ProcessMaker/processmaker#3211]
**Describe the bug**
While exporting the process there is a server error in https://{{username}}.developer.beta.processmaker.net

**To Reproduce**
1. Go to ' Designer -> Processes -> Export menu'
2. Click on 'Download'
4. See error as "Server Error"

**Expected behavior**
The process has to download

**Screenshots**
![screen 6](https://user-images.githubusercontent.com/27679841/85147612-be787980-b26c-11ea-992b-4428fa8800ac.PNG)

**Desktop (please complete the following information):**
 - OS: windows 10pro
 - Browser [chrome]
 - Version [version 83.0.4103.106]
- php version 7.3

**Comment by velkymx** [comment]
Can you post the output of your log file? It's located in the storage/logs folder of your installation.

**Comment by jemiris** [comment]
Opps, its Developer Beta Processmaker Server provided from Processmaker4 instance. 

[https://jemiris.developer.beta.processmaker.net/](url)

**Comment by velkymx** [comment]
@jemiris please reach out to ProcessMaker sales person. Looks like your instance is not active or having an issue. They can help you to get support.
