### ISSUE TITLE
Request Pagination Hidden

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#3213]
Steps to Reproduce:

Go to the requests page

Go to the last page, this one must not be full

change the pagination to select 50 items

Current Behavior:
The pagination controller and the items disappear, there is no way to recover them without refreshing

**Comment by PMQABen** [comment]
https://processmaker.atlassian.net/browse/FOUR-1449

**Comment by ZLTM** [comment]
Still replicating on release testing
https://www.dropbox.com/s/4vxt4rzic666w7b/2020-07-06%2017-03-53.mp4?dl=0

**Comment by marcoAntonioNina** [comment]
@ZLTM the paginator is not displayed when the number of items is less that the selected in dropdown, it  works in this way by default.

**Comment by PMQABen** [comment]
Expected behavior from the JIRA ticket:
The pagination controller must always be available to allow the user to change its selection

**Comment by PMQABen** [comment]
Looks like this has created an unexpected error when looking at the bottom of the Process page when there are 0 or 1 processes created:
![image](https://user-images.githubusercontent.com/28575916/87460239-64e04200-c5c1-11ea-9dc6-39b7928f8ff1.png)

**Comment by ZLTM** [comment]
Working on release after the update

**Comment by PMQABen** [comment]
More problems found:
![image](https://user-images.githubusercontent.com/28575916/87584234-08992300-c692-11ea-8825-8a7e89b26f66.png)
