### ISSUE TITLE
PMQL: 500 ISE "Trying to get property 'id' of non-object"

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#3214]
Description
From inside /requests, run a PMQL search:

participant = "invalidusername"

Result:
```
500 ISE "Trying to get property 'id' of non-object"

GET https://staging-pm4qa.processmaker.net/api/1.0/requests?page=1&per_page=10&include=process,participants,data&pmql=participant%20%3D%20%22invalidusername%22&filter=&order_by=id&order_direction=DESC 500

exception: "ErrorException"
file: "/opt/processmakerqa/ProcessMaker/Models/ProcessRequest.php"
line: 565
message: "Trying to get property 'id' of non-object"
```
In 406, "Server Error" is seen as a banner error, and the console log shows this:
`GET https://cloudops-staging.processmaker.net/api/1.0/requests?page=1&per_page=10&include=process,participants,data&pmql=participant%20%3D%20%22invalidusername%22&filter=&order_by=id&order_direction=DESC 500`

Expected:
Return the message "no data available" in the main results.

**Comment by PMQABen** [comment]
Still getting the same error in release-testing running "4.0.7 Develop."

**Comment by sanjacornelius** [comment]
Can't reproduce locally.

**Comment by PMQABen** [comment]
I'm wondering if the release-testing server needs to be re-upgraded to the 407 code.

**Comment by PMQABen** [comment]
User error on my part. I was testing `requester = "invaliduser"` and not `participant = "invaliduser"`

I'll make a new JIRA ticket later for the requester version of this error.
