### ISSUE TITLE
Screen / Script Selects

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#3218]
When assigning a script or screen using the multi-select control the type ahead search is searching too much data. Should only be filtering by the name of the asset.

![image](https://user-images.githubusercontent.com/535300/85299831-a2d2c600-b45a-11ea-8c2e-5b3d0879d99a.png)

**Comment by PaolaPellegrini** [comment]
The suggest of the name is not displayed correctly.

I have several examples with the name screen Ascreen, Screen_Paola, Test_Screen, etc.


And when I start putting scr it doesn't show me first the ones that start with that name, it's showing all the suggestions

![Issue3218](https://user-images.githubusercontent.com/51709910/86179247-e6cb6800-baf7-11ea-879a-98dcd6af2f52.png)

we can improve that search.

Showing the first matches and then what follows

**Comment by sanjacornelius** [comment]
Cannot reproduce this locally

**Comment by sanjacornelius** [comment]
> The suggest of the name is not displayed correctly.
> 
> I have several examples with the name screen Ascreen, Screen_Paola, Test_Screen, etc.
> 
> And when I start putting scr it doesn't show me first the ones that start with that name, it's showing all the suggestions
> 
> ![Issue3218](https://user-images.githubusercontent.com/51709910/86179247-e6cb6800-baf7-11ea-879a-98dcd6af2f52.png)
> 
> we can improve that search.
> 
> Showing the first matches and then what follows

Cannot reproduce this locally

**Comment by PMQABen** [comment]
We need to get release-testing properly updated with the new code.

**Comment by velkymx** [comment]
This returned sorting is correct. The search, in this example, is just returning by alpha with the containing string. We aren't doing a fuzzy search like you'd find in Google or similar search engines.

**Comment by PaolaPellegrini** [comment]
Taking that acceptance criteria, the solution is approved
