### ISSUE TITLE
Mustache formatting issues

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#3220]
Forms are displaying Ampersands and Apostrophes as code instead of as the character.

![image](https://user-images.githubusercontent.com/535300/85301124-4a9cc380-b45c-11ea-9ca6-018d1a4cc8f4.png)

**Comment by PMQABen** [comment]
Still occurring in release-testing.

**Comment by sanjacornelius** [comment]
> Still occurring in release-testing.

Looks like the PR still needs to be merged.
