### ISSUE TITLE
Update Node Executor to v12 LTS

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#3222]
Update the docker to use the LTS version of NodeJS

Also update Circle CI to use v12 of node and the LTS version of npm

Also double check vagrant that it also uses the LTS version

**Comment by PMQABen** [comment]
**QA Note --** Use the following code to find the Node version:
```
return new Promise((resolve,reject) => {
    const { exec } = require('child_process');
    exec('node -v', function(error, stdout, stderr) {
        resolve({'version':stdout});
    });
});
```
