### ISSUE TITLE
Add required option to file upload

### ISSUE THREAD

**Issue by nolanpro** [ProcessMaker/processmaker#3231]
Refs https://github.com/ProcessMaker/screen-builder/issues/763

**Comment by PaolaPellegrini** [comment]
An observation has been found.
It should show a message that the file is required when we try to derive the task with the required file empty.

See  the video https://drive.google.com/file/d/1ekvWQrwBsH94GZ6tXAkbBd0rFzMolkRu/view?usp=sharing

**Comment by PMQABen** [comment]
I am confused. The video shows the red "required" text next to the "select file" button, and the submit button does not work if the file is not attached. How is this not working as intended?

**Comment by ZLTM** [comment]
The issue would be we need a notification informing the user that a specific field is required, this will be really useful while working on big screens with many controllers, however, I do think that would be a different ticket
The corresponding Jira ticket is this one
https://processmaker.atlassian.net/browse/FOUR-1687
