### ISSUE TITLE
Make Start Buttons into HTML links

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#3233]
I want to be able to copy-and-paste the start URL from the html button. Right now it is a JavaScript button. 

![image](https://user-images.githubusercontent.com/535300/85878602-d3ce3600-b78d-11ea-8348-0a4a4ad03271.png)

Right click and "copy link" needs to work

**Comment by PaolaPellegrini** [comment]
You can now copy the link to the start button, but when I copy it to another tab the link does not work.

if the path can be copied, it should work. See  the  video  https://drive.google.com/file/d/1E5VmTmzE6vykw5GDCAjd-buhzld304V8/view?usp=sharing

The solution is not approved

**Comment by PaolaPellegrini** [comment]
The solution is  approved!
