### ISSUE TITLE
Running docker-executor-lua:install sh: 1: docker: not found

### ISSUE THREAD

**Issue by jemiris** [ProcessMaker/processmaker#3243]
**Describe the bug**

While installing the `php artisan processmaker:install` some of the tables are migrated. After that there is an issue

**To Reproduce**

1. Go to 'Installation of processmkaer 4' `php artisan processmaker:install `. 
2. See error

**Screenshots**
![screen 7](https://user-images.githubusercontent.com/27679841/86559207-10154980-bf79-11ea-8c2a-7019e1054b7d.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10 pro]
 - php Version [ PHP 7.3.12 ]
- node [ v12.16.1 ]
- Vagrant 2.2.9
- Docker version 19.03.8

**Comment by velkymx** [comment]
Looking at the error message, it seems to be failing at:

`ErrorException: mkdir(): File exists`

Try deleting that Lua docker file and trying again.

**Comment by jemiris** [comment]
Could you tell me where can I find the Lua docker file to delete?

**Comment by minger0** [comment]
the same happened to me during an install in Ubuntu, when starting up the 'php artisan processmaker:install' the first time

**Comment by velkymx** [comment]
@jemiris run the docker command `docker images` to locate the docker files

**Comment by nolanpro** [comment]
@jemiris can you confirm you have docker installed in your vagrant machine? `docker --version` when ssh'd into your vagrant box?

**Comment by haris-raheem** [comment]
docker is not listed under requirements in Readme.md. does it need an update?

**Comment by haris-raheem** [comment]
i have installed docker and now it works. so readme.md must be updated to include docker as requirement

**Comment by velkymx** [comment]
Excellent. Closing!
