### ISSUE TITLE
Large request volumes/large data objects Cause API Timeouts

### ISSUE THREAD

**Issue by ryancooley** [ProcessMaker/processmaker#3245]
When returning a large volume of requests, the API is displaying a timeout error.  This is happening when they click on "All Request" and "In Progress" requests. 

![image](https://user-images.githubusercontent.com/535300/87048493-a0899f00-c1b0-11ea-851f-54cdb675c936.png)

Related to: https://processmaker.atlassian.net/browse/FOUR-1686

**Comment by PMQABen** [comment]
It's weird, because I swear that I've seen servers with larger amounts of request data not having this issue. We're going to need Ops to `artisan tinker` us a _whoooooole_ lot of requests for testing.

**Comment by velkymx** [comment]
@PMQABen this is ready on develop. Go crazy!

**Comment by PMQABen** [comment]
We created 14,000 requests. 10k of which are completed, the rest are "in progress." When logged in as the admin user, requests in all the tabs load as expected, no API timeouts. When using a non-admin account with "view all requests" permissions, the requests do not load and I get console errors:

```
[Error] [Vue warn]: Error in event handler for "api-client-error": "TypeError: undefined is not an object (evaluating 'error.response.data')"
(found in <Root>)
	warn (vendor.js:115688)
	logError (vendor.js:116947)
	globalHandleError (vendor.js:116942)
	handleError (vendor.js:116902)
	invokeWithErrorHandling (vendor.js:116925)
	(anonymous function) (vendor.js:118943)
	(anonymous function) (app-layout.js:485154)
	promiseReactionJob

[Error] TypeError: undefined is not an object (evaluating 'error.response.data') — index.js:2072
	logError (vendor.js:116951)
	globalHandleError (vendor.js:116942)
	handleError (vendor.js:116902)
	invokeWithErrorHandling (vendor.js:116925)
	(anonymous function) (vendor.js:118943)
	(anonymous function) (app-layout.js:485154)
	promiseReactionJob

[Error] Unhandled Promise Rejection: Error: timeout of 25000ms exceeded
	(anonymous function) (index.js:2502)
	promiseReactionJob
```

**Comment by velkymx** [comment]
This fix improves performance of this page by 2x and we feel it fixes the issues. We've also added an API timeout flag and more memory to that server.
