### ISSUE TITLE
Change bootstrap.json timeout to 0 to allow timeout to be controlled by PHP

### ISSUE THREAD

**Issue by Kookster310** [ProcessMaker/processmaker#3257]
**Describe the bug**
We're not currently able to adjust execution timeout values via php. The timeout is hardcoded into the bootstrap.json during build:
`window.ProcessMaker.apiClient.defaults.timeout = 5000;`

If we set the timeout to 0, this would allow us to control the timeout execution time via php configuration settings on the server.

**Comment by velkymx** [comment]
This has been deployed
