### ISSUE TITLE
Horizon broken

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#3262]
Failed to compile with 15 errors          5:43:28 PM

These dependencies were not found:

* Horizon/components/App in ./resources/js/admin/queues/index.js
* Horizon/components/Status/Loader.vue in ./resources/js/admin/queues/index.js
* Horizon/components/Status/Status.vue in ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers":false}]],"babelrc":false,"env":{"****":{"presets":[["env",{"targets":{"node":"current"}}]]},"development":{"presets":[["env",{"modules":false,"targets":{"browsers":"> 2%","uglify":true}}]]},"production":{"presets":[["env",{"modules":false,"targets":{"browsers":"> 2%","uglify":true}}]]}}}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./resources/js/admin/queues/layouts/MainLayout.vue
* Horizon/layouts/MainSidebar.vue in ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers":false}]],"babelrc":false,"env":{"****":{"presets":[["env",{"targets":{"node":"current"}}]]},"development":{"presets":[["env",{"modules":false,"targets":{"browsers":"> 2%","uglify":true}}]]},"production":{"presets":[["env",{"modules":false,"targets":{"browsers":"> 2%","uglify":true}}]]}}}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./resources/js/admin/queues/layouts/MainLayout.vue
* Horizon/pages/Dashboard.vue in ./resources/js/admin/queues/router.js
* Horizon/pages/Failed/Index.vue in ./resources/js/admin/queues/router.js
* Horizon/pages/Failed/Job.vue in ./resources/js/admin/queues/router.js
* Horizon/pages/Metrics/Index.vue in ./resources/js/admin/queues/router.js
* Horizon/pages/Metrics/Jobs.vue in ./resources/js/admin/queues/router.js
* Horizon/pages/Metrics/Metric.vue in ./resources/js/admin/queues/router.js
* Horizon/pages/Metrics/Queues.vue in ./resources/js/admin/queues/router.js
* Horizon/pages/Monitoring/Index.vue in ./resources/js/admin/queues/router.js
* Horizon/pages/Monitoring/Jobs.vue in ./resources/js/admin/queues/router.js
* Horizon/pages/Monitoring/Tag.vue in ./resources/js/admin/queues/router.js
* Horizon/pages/RecentJobs/Index.vue in ./resources/js/admin/queues/router.js

**Comment by nolanpro** [comment]
Done as part of https://github.com/ProcessMaker/processmaker/issues/3251
