### ISSUE TITLE
Gateway Flow Variable Refactor

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#3276]
Update to match mock up.

![image](https://user-images.githubusercontent.com/535300/87815082-d1557e00-c819-11ea-836a-e3a560fa3836.png)

**Comment by PMQABen** [comment]
Tried to use this in a process and it returned an error in the process after I clicked the "no" button:
```
Argument 2 passed to Illuminate\Log\LogManager::error() must be of the type array, string given, called in /opt/release-testing/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 239
```
![image](https://user-images.githubusercontent.com/28575916/90812964-c17aff00-e2db-11ea-98ed-cf3d2b09af14.png)
![image](https://user-images.githubusercontent.com/28575916/90813054-e0799100-e2db-11ea-8d89-586116576af3.png)

**Comment by PMQABen** [comment]
So I pulled the new merged code onto my local VM, and I think the Flow Variable bit is still not working as expected. I rebuilt the process seen above, and even though the routing works, it hides an error message about it in the `_request` data:
```
"errors": [
    {
        "body": "",
        "message": "The expression \"Nope!\" is invalid. Please contact the creator of this process to fix the issue. Original error: \"Variable \"Nope\" is not valid around position 1 for expression `Nope!`.\"",
        "created_at": "2020-08-20T23:13:13+00:00",
        "element_id": "node_4",
        "element_name": "Exclusive Gateway"
    }
],
```
