### ISSUE TITLE
composer install bug

### ISSUE THREAD

**Issue by 296721605** [ProcessMaker/processmaker#3290]
##version:4.1
###When I use composer to install, halfway through the installation, the following error will be prompted:
[RuntimeException]                                                                                                      
  Source path "/var/packages/ProcessMaker/docker-executor-lua" is not found for package processmaker/docker-executor-lua 
![image](https://user-images.githubusercontent.com/9688306/88251278-f1cf7d80-ccdc-11ea-9da6-580a4a537cff.png)

##version:4.0.3
When I use composer to install, halfway through the installation, the following error will be prompted:
### Invalid zip file, retrying...
  - Installing laravel/dusk (v5.9.0): Downloading (connecting...)

**Comment by unibravo** [comment]
I have same ıssue

**Comment by allanregistos** [comment]
The offending file is: _composer.lock_ located in the main directory. I've deleted it and the installation proceeded.

**Comment by Vitexus** [comment]
Maybe note in README's Installation section can solve this problem as well ?

**Comment by nolanpro** [comment]
Looks like there might be a problem with the checked-in version of composer.lock. Can you delete it and try `composer install` again?

**Comment by MRROOX** [comment]
> The offending file is: _composer.lock_ located in the main directory. I've deleted it and the installation proceeded without any issues.

This work for me !
