### ISSUE TITLE
Identity & Access Management: Session timeout

### ISSUE THREAD

**Issue by gustavo-romero** [ProcessMaker/processmaker#3309]
**Describe the bug**
As per [HIPAA / HITECH Act 164.312(a)(2)(iii](https://www.hhs.gov/sites/default/files/ocr/privacy/hipaa/administrative/securityrule/techsafeguards.pdf)), [ISO 27001:2013 A 11.5.5](https://www.iso.org/standard/54534.html),[ PCI DSSv3.2 8.1.8](https://www.pcisecuritystandards.org/documents/Prioritized-Approach-for-PCI_DSS-v3_2.pdf) web applications shall set automatic session termination after a specific idle timeout.

Although most security compliance standards do not set a specific timeout, as a best security practice, the default session timeout should be set to 15 minutes as suggested by [OWASP](https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html) - while PCI DSS v3.2 does set a hard 15 minute requirement.

**Expected behavior**
Currently, ProcessMaker 4 sets a default of 2 hours idle session timeout. As a best security practice, the default should be set to 15 minutes for highly-sensitive environments, such as banking/payment industry projects.  
In the future, this could be configurable from the Admin UI.

The proposed change can be found in https://github.com/ProcessMaker/processmaker/pull/3308

**Comment by velkymx** [comment]
@gustavo-romero this is an excellent suggestion and I will forward it to the CloudOps team to add to their deployment. 

Ref: SCO-6279
