### ISSUE TITLE
Identity & Access Management: Cookie security

### ISSUE THREAD

**Issue by gustavo-romero** [ProcessMaker/processmaker#3311]
**Describe the bug**
As per [OWASP](https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html), in order to prevent session hijacking, a series of best practices are recommended. A web application should by default enforce a secure baseline for session cookie management.

**Expected behavior**
The ProcessMaker 4 session cookies should enforce by default:
- **Secure Cookie Attribute**. The _Secure_ cookie attribute instructs web browsers to only send the cookie through an encrypted HTTPS (SSL/TLS) connection. Forcing the web application to only use HTTPS for its communication (even when port TCP/80, HTTP, is closed in the web application host) does not protect against session ID disclosure if the Secure cookie has not been set
- **Same-Site Cookie Attribute**. The Same-Site attribute allows a server sets a preventive flag making it impossible to the browser send the cookie along with cross-site requests, effectively preventing CSRF.
- **Disable Session Persistence**.  It is highly recommended to use non-persistent cookies for session management purposes, so that the session ID does not remain on the web client cache for long periods of time, from where an attacker can obtain it. When a browser is closed, the session should

The proposed changes can be found in https://github.com/ProcessMaker/processmaker/pull/3310
- Set the secure cookie attribute (Secure channel for session cookie transmission)
- Set the expire_on_close attribute (End session on browse close)
- Set the Same-Site cookie flag (Prevent CSRF)

**Comment by velkymx** [comment]
@gustavo-romero I've forwarded this on to the CloudOps team to configure cookies in the deployment. 

Ref: SCO-6280
