### ISSUE TITLE
Magic vars in a process_request data object are cluttered

### ISSUE THREAD

**Issue by nolanpro** [ProcessMaker/processmaker#3316]
The data field is cluttered with magic vars when a process is active. This is causing search problems.

Our 3 magic vars: _request, _user, and _parent are using the default laravel serializer that includes all relationships.

The simplest solution is to explicitly use `attributesToArray()` when setting the magic var.

Ideally, the magic var would never actually persist in the data object, however that would be a much larger project to implement.

**Comment by velkymx** [comment]
This has been deployed
