### ISSUE TITLE
BPMN Export Missing Elements due to Non-standard Characters

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#3328]
When attempting to export a BPMN file from a process design, if the BPMN has issues, the export is incomplete.

There are two issues here: 

1. Non-standard characters are allowed that break the BPMN standard
2. This non-standard characters makes the export incomplete.

Fixes:

Do not allow non-standard characters to be entered into the BPMN schema.

Check the export works properly and includes all of the proper config. I'm attaching two files. The first it the export and the second is the actual BPMN. Both files are from the same process.

[incomplete-export.xml.txt](https://github.com/ProcessMaker/processmaker/files/5042480/incomplete-export.xml.txt)

[complete-export.xml.txt](https://github.com/ProcessMaker/processmaker/files/5042482/complete-export.xml.txt)

**Comment by ryancooley** [comment]
Testing locally, I’m not able to reproduce. I can export and import with special characters including emoji.

**Comment by velkymx** [comment]
Great. Marking as fixed
