### ISSUE TITLE
Make dynamic labels for buttons or other elements

### ISSUE THREAD

**Issue by cyberiums** [ProcessMaker/processmaker#3379]
Hi,

I am looking for ways or suggestions to make the name value of buttons dynamic. I have a loop control with buttons. A number of buttons get created based on the date selection. The loop data is as follows:
```
[{
time: 1000
},
{
time: 1100
},
{
time: 1200
}]
```

Based on above data for loop control, 3 buttons get created. But I am not able to set the name/value of buttons. Is there a way to show the name value of each buttons like:
```

Book meeting @ 10
Book meeting @ 11
Book meeting @ 12
```

**Comment by velkymx** [comment]
@cyberiums Inside of a loop reference the `_parent` object to call the array data.

See the documentation on loops here:
https://processmaker.gitbook.io/processmaker/designing-processes/design-forms/screens-builder/control-descriptions/loop-control-settings
