### ISSUE TITLE
Cannot Login

### ISSUE THREAD

**Issue by tschmitzce** [ProcessMaker/processmaker#3385]
After Booting VM. When I try to login with the credentials I have set, the page just redirects to login again.

I logged into the mysql instance and the 'loggedin_at' attribute is being updated when I login using the correct credentials.

**Expected behavior**
I am logged in

**Desktop (please complete the following information):**
 I am using all the specified versions of Composer, Vagrant, Node, VirtualBox, and Vagrant
Tried in Google Chrome and Firefox

**Comment by tschmitzce** [comment]
Edit: Login Works in v4.0.8 but not v4.1

**Comment by iyawat** [comment]
I have the same issue. How can I switch to V4.0.8?

**Comment by tschmitzce** [comment]
After cloning the repo and going into it, do `git checkout tags/v4.0.8`

**Comment by iyawat** [comment]
Thanks, @tschmitzce .. I confirmed as V.4.0.8 can do login..

**Comment by sakmon** [comment]
I have the same issue. cannot login in v4.0.16.

**Comment by Jatin21** [comment]
Does anyone able to fix the login issue in the latest verison? I am facing the same issue, it is throwing me back at login screen on each login. Looks like the session is not getting established. I'm on php 7.4 on ubuntu 20.04.

**Comment by JackWangz** [comment]
Any update?
I have the same issue in v4.1.19.

**Comment by ameed-aabidi** [comment]
Same issue with  ProcessMaker 4 v4.2.29
Any updates?
