### ISSUE TITLE
Class 'ProcessMaker\Package\DockerExecutorNode\DockerExecutorNodeServiceProvider' not found 

### ISSUE THREAD

**Issue by hmdshariati** [ProcessMaker/processmaker#3406]
Class 'ProcessMaker\Package\DockerExecutorNode\DockerExecutorNodeServicePro  
  vider' not found 
cannot use version 4.1

**Comment by velkymx** [comment]
This issue has been resolved. 4.1  is currently the development branch and we recommend you grab the 4.0.x until 4.1 is released.
