### ISSUE TITLE
upgrade to laravel7

### ISSUE THREAD

**Issue by mahdi29sh** [ProcessMaker/processmaker#3481]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
please upgrade laravel version to 7

**Comment by velkymx** [comment]
We will not be upgrading to Laravel 7. We will continue on the LTS branch until a now LTS is released. Right now there is too much flux in the Laravel stack.
