### ISSUE TITLE
upgrade latest version of laravel 

### ISSUE THREAD

**Issue by a-bahrami** [ProcessMaker/processmaker#3488]
hello 
Thank you very much for making this great package, but still this good package should support the latest version of Laravel to be a better user to the users of this system. So please update this package to the latest Laravel version as soon as possible .

**Comment by velkymx** [comment]
We will not be upgrading to Laravel 7/8. We will continue on the LTS branch until a new Long Term Support version is released. Right now there is too much flux in the Laravel stack.
