### ISSUE TITLE
SignalSeeder or UserSeeder?

### ISSUE THREAD

**Issue by windqyoung** [ProcessMaker/processmaker#3504]
https://github.com/ProcessMaker/processmaker/blob/0a4d82f071c539bbad37ebc7bad2aef1d25a3615/ProcessMaker/Console/Commands/Install.php#L330

   Symfony\Component\Debug\Exception\FatalThrowableError  : Access to undeclared static property: SignalSeeder::$INSTALLER_ADMIN_USERNAME

  at D:\projects\processmaker\ProcessMaker\Console\Commands\Install.php:330
    326|             }
    327|             $validator = $this->validateField('lastname', $lastname, ['max:50']);
    328|         } while($validator->fails());
    329|         // Set the default admin properties for UserSeeder
  > 330|         SignalSeeder::$INSTALLER_ADMIN_USERNAME = $username;
    331|         SignalSeeder::$INSTALLER_ADMIN_EMAIL = $email;
    332|         SignalSeeder::$INSTALLER_ADMIN_PASSWORD = $password;
    333|         SignalSeeder::$INSTALLER_ADMIN_FIRSTNAME = $firstname;
    334|         SignalSeeder::$INSTALLER_ADMIN_LASTNAME = $lastname;

**Comment by velkymx** [comment]
We've noticed a number of issues installing on Windows machines. We recommend you use AWS Linux.
