### ISSUE TITLE
Wrong ProcessMaker version in the System Information page

### ISSUE THREAD

**Issue by jotamartos** [ProcessMaker/processmaker#3561]
**Describe the bug**
I just downloaded and deployed ProcessMaker Open Source 4.0.15 using the package you provide here

https://github.com/ProcessMaker/processmaker/releases/tag/v4.0.15

However, when clicking on Admin > System information, I can see this

![image](https://user-images.githubusercontent.com/8791635/101788436-61b19980-3b00-11eb-8068-384979e4cad4.png)

Apart from that, I saw that PM 4.x is not listed in the main site, that makes me wonder if I should use ProcessMaker 4. Is PM 4.x stable or should we continue using PM 3.2 as the main site shows?

https://www.processmaker.com/products/open-source-downloads/

**To Reproduce**
1. Access ProcessMaker Open Source 4.0.15
2. Click on Admin > System information
3. Get the app's version

**Expected behavior**
4.0.15 is supposed to be shown there

**Screenshots**
Check the description

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 83.0

**Additional context**

**Comment by velkymx** [comment]
Looks like you've installed ProcessMaker 3! I would absolutely recommend you try out ProcessMaker 4. It's been out for a while now and is ready for your project!

Direct link to the latest version: https://github.com/ProcessMaker/processmaker/releases/download/v4.0.15/processmaker4.0.15.tar.gz
