### ISSUE TITLE
error when run npm install

### ISSUE THREAD

**Issue by majidsoltani** [ProcessMaker/processmaker#3589]
hi
when i have do install npm packages ,

occured this error :

-----------------------------------------
The syntax of the command is incorrect.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @processmaker/processmaker@4.1.0 postinstall: `mkdir -p public/css/precompiled && cp -rf node_modules/npm-font-open-sans public/css/precompiled/npm-font-open-sans && cp -rf node_modules/bootstrap/scss public/css/precompiled/bootstrap && cp -rf node_modules/@fortawesome/fontawesome-free public/css/precompiled/fontawesome-free && cp -rf node_modules/vue-multiselect/dist/vue-multiselect.min.css public/css/precompiled`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @processmaker/processmaker@4.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\devma\AppData\Roaming\npm-cache\_logs\2020-12-22T21_05_50_402Z-debug.log
----------------------------

please help me, how i can solve this problem

**Comment by cybrpimp** [comment]
What was the solution to this?  I'm having the exact same problem.
