### ISSUE TITLE
bug in submit button (screen)

### ISSUE THREAD

**Issue by Smidaa** [ProcessMaker/processmaker#3595]
when click on Submitt button the variable value still null ( when running the process ) => can't use it in the exclusive gateway for example

**Comment by Smidaa** [comment]
![image](https://user-images.githubusercontent.com/32571168/103406520-4106bd80-4b5b-11eb-85da-40702a72dbdb.png)

![image](https://user-images.githubusercontent.com/32571168/103406561-6267a980-4b5b-11eb-8559-0280b26f292e.png)

**Comment by Smidaa** [comment]
"approval" should be yes not null

**Comment by velkymx** [comment]
@Smidaa agreed. We can't reproduce the issue on our end. What version are you using?

![image](https://user-images.githubusercontent.com/535300/112323172-e9727c80-8c87-11eb-942d-86664ef114fe.png)

**Comment by velkymx** [comment]
No response. Closing ticket.
