### ISSUE TITLE
Error execute script /Designer/Scripts/<script name> 

### ISSUE THREAD

**Issue by carlosmorenoaguilera** [ProcessMaker/processmaker#3599]
**Describe the bug**
Error with not output when trying to execute simple script 

**Screenshots**
![image](https://user-images.githubusercontent.com/68555049/103606361-ced80500-4edb-11eb-84b4-e4dacf3539a1.png)
no output, infinite charging circle. 
![image](https://user-images.githubusercontent.com/68555049/103606106-46f1fb00-4edb-11eb-9d15-6d5dad566a14.png)
![image](https://user-images.githubusercontent.com/68555049/103606238-8ddff080-4edb-11eb-94a9-759e1e0412e4.png)

**Desktop (please complete the following information):**
 - OpenSuse 15.2
 - Firefox 68.9.esr (64bits)

**Comment by velkymx** [comment]
@carlosmorenoaguilera it seems your jobs are not running. You need to enable [Laravel Scheduling](https://laravel.com/docs/5.8/scheduling) another item of note is it is showing socket.io is not responding, have you configured the socket.io settings needed for [Laravel Broadcasting](https://laravel.com/docs/5.8/broadcasting)?
