### ISSUE TITLE
Error in npm install

### ISSUE THREAD

**Issue by chiragkanhasoft** [ProcessMaker/processmaker#3605]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

![image](https://user-images.githubusercontent.com/27885527/103978285-2ce93e80-51a1-11eb-8030-251ec39c4cd9.png)

**Comment by velkymx** [comment]
In examining the logs it appears you are using an outdated version of Node (8.10.0) in your attempt to install. Make sure your system meets the requirements in the readme.
