### ISSUE TITLE
Install Step composer install --no-dev runs into  Class 'Laravel\Dusk\DuskServiceProvider' not found

### ISSUE THREAD

**Issue by martinpetermichael** [ProcessMaker/processmaker#3636]
**Describe the bug**
When using the command `composer install --no-dev` I'm getting 
```
[Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'Laravel\Dusk\DuskServiceProvider' not found
```

Server Ubuntu 20.04. fresh install. PHP 7.4 / nginx
Followed the decribed Steps.
Also tried to use composer update and --with-all-dependencies but same error.

**Comment by tsdogs** [comment]
Problem is that default environment when installing is "local"
In the source code there is a test if environment is not production it registers the dusk provider.

I changed line 69 of ProcessMaker/Providers/ProcessMakerServiceProvider.php to temporarily fix the problem to
```
       if(!$this->app->environment('production') && !$this->app->environment('local')) {
```

**Comment by velkymx** [comment]
@tsdogs right on! The dusk provider is part of the dev environment for testing. Changing to production will remove that requirement.

**Comment by iamaer4fa** [comment]
> 
> 
> @tsdogs right on! The dusk provider is part of the dev environment for testing. Changing to production will remove that requirement.

This might be related.
https://github.com/laravel/dusk/issues/289#issuecomment-344273543
