### ISSUE TITLE
It is redirected to Login page on every process

### ISSUE THREAD

**Issue by serkanerdinc** [ProcessMaker/processmaker#3716]
After the first setup, I enter the user information of the Login screen. But it is throws on the Login page again. I am sure I have entered the password correctly. Although I change the password and repeatedly set up it is the same problem.

ProcessMaker Version: 4.1
System: Ubuntu 20.04

**Comment by velkymx** [comment]
@serkanerdinc can you check the logs in the storage/logs folder? Also how did you go about changing the password?

**Comment by serkanerdinc** [comment]
I haven't been a problem when I do the same transactions in version 4.0.8. But in version 4.1 I have never been logged in.

**Comment by velkymx** [comment]
If you are moving from 4.0 to 4.1 - you will need to upgrade PHP to 7.4 and rebuild the cache.

**Comment by Jatin21** [comment]
@serkanerdinc Have you able to fix this. I am facing the same issue, it is throwing me back at login screen on each login. Looks like the session is not getting established. I'm on php 7.4 on ubuntu 20.04.
