### ISSUE TITLE
Processmaker 4.0.8 New Request Server Error

### ISSUE THREAD

**Issue by gunerfurkanilker** [ProcessMaker/processmaker#3720]
I'm getting error when i'm trying to create a request. Service url is /process_events/{process_id}.

It returns the server error, creating request somehow but it has empty data value. I debugged the code in order to find which line of code giving the error and i suspect this is the code i'm getting the error.

`//Trigger the start event
        $processRequest = WorkflowManager::triggerStartEvent($process, $event, $data);`

Has anyone got the solution of this problem or getting this error like me ?

Thanks already for your help

Regards

**Comment by velkymx** [comment]
@gunerfurkanilker very interesting. Please upgrade to the latest version of ProcessMaker 4 - v4.1
