### ISSUE TITLE
Extensibility

### ISSUE THREAD

**Issue by coconutdad** [ProcessMaker/processmaker#3722]
Is ProcessMaker 4.x extensible?  I would like to develop my own data connectors, plugins, etc.

Is there any documentation on this?

Thanks
James

**Comment by velkymx** [comment]
@coconutdad it is extensible! We recommend you use the [Script Tasks](https://processmaker.gitbook.io/processmaker/designing-processes/process-design/model-your-process/add-and-configure-script-task-elements) to accomplish this. With a script task you can connect to any third party system or do any custom coding!
