### ISSUE TITLE
Install instruction do not work as many people have reported

### ISSUE THREAD

**Issue by cybrpimp** [ProcessMaker/processmaker#3726]
We were looking to migrate from Camunda but the installation does not work.

To much trouble so we gave up.

Best of luck and hopefully you get the problems solve do ProcessMaker can grow.

**Comment by coconutdad** [comment]
[process maker Install steps.docx](https://github.com/ProcessMaker/processmaker/files/6191041/process.maker.Install.steps.docx)

Yes!!! Process Maker is an SOB to get installed!!  I tried 6 separate times prior to making it work.  The last time I wrote every step I took and I was finally successful.  Hopefully this helps somebody.

I am still disappointed with Process Maker overall.  While it is "open source" it seems to anything worthwhile in it you will need move to the paid version.  

As a developer, I was hoping to write my own modules, etc.  It doesn't seem to be an option.

**Comment by velkymx** [comment]
@coconutdad wonderful tips in the document. As a developer, we recommend you run the install using the Homestead/Vagrant settings which will not require any of those steps. Just `vagrant up` and you are good to go! If you are looking to try ProcessMaker 4 - we do offer host trial instances and you can request them here: https://www.processmaker.com/request-demo/
