### ISSUE TITLE
New nodes or node types for existing ones

### ISSUE THREAD

**Issue by CrossPDev** [ProcessMaker/processmaker#3727]
Hello awesome Processmaker team, 

I'd like to know how to add fully new node types oder fully new nodes to the modeler.
I already managed adding new Screen-Builder elements without messing around with other repositories other than the processmaker base project.

Is there any documentation I can read up for my intentions?

To be clear:
- I like to program new start node types
- I like to program new end node types
- I like to program fully new node types which behave differently than the current ones

I'd appreciate any help on how to achieve my goals.
Thanks in advance for reading all of this 😊

**Comment by velkymx** [comment]
Adding new types of elements to your BPMN would require adding the modeling aspect (in the modeler project), adding new functionality to the BPMN engine, and to the BPMN linter, and then bringing it all back together into the core project. Not a small undertaking! I would not be possible to do just in the ProcessMaker core project.
