### ISSUE TITLE
package.json Changes for Windows

### ISSUE THREAD

**Issue by ghamajid** [ProcessMaker/processmaker#3732]
Apply this change to package.json file if you are using Windows

"postinstall": "xcopy /S node_modules\\npm-font-open-sans public\\css\\precompiled\\npm-font-open-sans && xcopy  /S node_modules\\bootstrap\\scss public\\css\\precompiled\\bootstrap && xcopy /S node_modules\\@fortawesome\\fontawesome-free public\\css\\precompiled\\fontawesome-free && xcopy /S node_modules\\vue-multiselect\\dist\\vue-multiselect.min.css public\\css\\precompiled",

**Comment by velkymx** [comment]
I do not recommend you install ProcessMaker 4 on Windows, unless you are using something like the docker version. For server installation we recommend Amazon Linux.
