### ISSUE TITLE
how can I contribute with processmaker?

### ISSUE THREAD

**Issue by hmdshariati** [ProcessMaker/processmaker#3737]
I was working on processmaker from version 2.
now that it's developing with laravel and vue and docker, I'm intresting in contribute to develop it to improve my resume.
how can I see the roadmap and be a little member of your team?

**Comment by velkymx** [comment]
@hmdshariati this is awesome! The best way to contribute is to use the software and report any issues you might find. If you fix the issue, even better, just put in a pull request and we will work to include it!
