### ISSUE TITLE
Plugin Development

### ISSUE THREAD

**Issue by kutayilkan** [ProcessMaker/processmaker#3738]
I read your ProcessMaker version 4 documentation and i couldn't find Plugin development for version 4. 
Old version of PM has it. (link below)
https://wiki.processmaker.com/3.0/Plugin_Development

Don't you support this feature in your new version? Or could I not find it? I will be glad if you help.

**Comment by velkymx** [comment]
ProcessMaker 4 does not have the concept of a plug-in. Ever our enterprise functionality is BPMN. We use our software to build our software!
