### ISSUE TITLE
"retry-script-tasks" command doesn't clear the Error

### ISSUE THREAD

**Issue by saadatfar** [ProcessMaker/processmaker#3747]
"retry-script-tasks" artisan command doesn't clear the error status of the request.

**Comment by velkymx** [comment]
Hi @saadatfar what are you trying to do? This command was specifically setup for when a script task becomes stuck due to a server crash.

**Comment by saadatfar** [comment]
I use it in situations like what you said. For example when a task results in an error because of a server network problem.

**Comment by velkymx** [comment]
This command will reset the task status, but not the request. I don't recommend using this functionality.
