### ISSUE TITLE
processmaker script task cannot run

### ISSUE THREAD

**Issue by BarryTsai0315** [ProcessMaker/processmaker#3851]
I use processmaker 4 versions 4.0.15 that I git clone from GitHub and I install it on the vagrant and run.

And I try to use the script task but it cannot return the value successfully, I also try to run the debugger mode. but it doesn't work. It just runs the circle at the bottom.

This is my script task
run Debugger mode and don't work

[https://i.stack.imgur.com/0e1NZ.png](url)

This is my process
[https://i.stack.imgur.com/RUekb.png](url)

**Comment by velkymx** [comment]
Have you tried SSH'ing into your vagrant and reviewing the logs? Is docker working correctly?

**Comment by velkymx** [comment]
You also need to make sure that the cron is properly configured for the Laravel installation. 

https://laravel.com/docs/6.x/scheduling#introduction

**Comment by jntdst** [comment]
I have same issue, I install pm4 from https://github.com/ProcessMaker/pm4core-docker and my version is 4.1.21 as same in docker file and I didn't change any things.
How can I config Laravel in docker?
please update docker repository to up to date .
