### ISSUE TITLE
Testing POST request not working as seen in University ProcessMaker tutorial

### ISSUE THREAD

**Issue by dafpogi** [ProcessMaker/processmaker#3867]
I am following how the speaker in University Processmaker did a PUT request and I followed how the request body was formatted just like in the API. 
![image](https://user-images.githubusercontent.com/67401292/123922169-55b4f880-d9ba-11eb-9195-7fb7e5f10a7e.png)
I input test data in the Test Request JSON, but the values do not appear in the response body.
![image](https://user-images.githubusercontent.com/67401292/123922466-a3316580-d9ba-11eb-85ce-a4bac439ecde.png)
Need your help on this. Thank you!

**Comment by velkymx** [comment]
Please reach to your training contact. They can help you with the examples.
