### ISSUE TITLE
This element is not expected

### ISSUE THREAD

**Issue by wsteven24** [ProcessMaker/processmaker#3869]
Getting an error when creating a new Process with Upload BPMN File:

DOMDocument::schemaValidate(): Element '{http://www.omg.org/spec/BPMN/20100524/MODEL}laneSet': This element is not expected. Expected is one of ( {http://www.omg.org/spec/BPMN/20100524/MODEL}resourceRole, {http://www.omg.org/spec/BPMN/20100524/MODEL}performer, {http://www.omg.org/spec/BPMN/20100524/MODEL}humanPerformer, {http://www.omg.org/spec/BPMN/20100524/MODEL}potentialOwner, {http://www.omg.org/spec/BPMN/20100524/MODEL}correlationSubscription, {http://www.omg.org/spec/BPMN/20100524/MODEL}supports ).

**Comment by velkymx** [comment]
@wsteven24 can you attach the BPMN file you are uploading? What software did you use to create this BPMN?
