### ISSUE TITLE
How to add a task to call an external payment system

### ISSUE THREAD

**Issue by EricRossC** [ProcessMaker/processmaker#3879]
Hi there!

I'm looking forward to use ProcessMaker, but many of my processes here need to use an external payment system. When running that task we need to pass control to the external site, and after the payment is complete, that system will call us back so we can resume our processing.

Is it possible? Is there any strategy to implement that?
Thanks in advance

Best regards

**Comment by velkymx** [comment]
@EricRossC Script Tasks are going to be a great solution for this! 

For example you could use the PHP Script to call out to a third party API via cURL. 

https://www.php.net/manual/en/ref.curl.php
