### ISSUE TITLE
Missing tarball for version 4.2.9

### ISSUE THREAD

**Issue by dgomezleon** [ProcessMaker/processmaker#3892]
The _processmaker4-v`VERSION`.tar.gz_ tarball is missing for the latest release 4.2.9. Do you plan to provide it? 

Apart from that, the [Release Notes site](https://processmaker.gitbook.io/processmaker-release-notes/) is still pointing to version 4.1.20. Should we consider 4.2.9 as the latest stable version?

**Comment by velkymx** [comment]
4.2.9 is a pre-release version and not for public consumption. Once we have a final release we will provide all the Release Notes, Files and Docker images to go along with it. Use 4.2 at your own risk.
