### ISSUE TITLE
Support for Google Analytics / Google Tag Manager in PM v4

### ISSUE THREAD

**Issue by jp-shields** [ProcessMaker/processmaker#3912]
Please support Google Analytics / Google Tag Manager in PM v4.
Ideally this would be set in admin/customize-ui and overridable in the form designer.
This should track all activity in the product, clients can configure Analytics to report the data they need.

Site: pm4ellucian.pm4trial

**Comment by velkymx** [comment]
Thank you @jp-shields I've noted your feature request.
