### ISSUE TITLE
Python Watcher error: Exception: Variable "output" must be a dict

### ISSUE THREAD

**Issue by jp-shields** [ProcessMaker/processmaker#3913]
**Describe the bug**
Python script error:
`Exception Variable "output" must be a dict`
Watcher settings is expecting an array
The translated PHP code runs just fine

**To Reproduce**
Python Code:
`output=json.loads('[{"name":"A","value":"A"},{"name":"B","value":"B"}]');`
PHP code:
`return json_decode('[{"name":"A","value":"A"},{"name":"B","value":"B"}]');`

**Expected behavior**
Should be able to return an array in both languages. Ideally however the watcher settings would be updated to support mapping more than one screen variable similar to the Data connector.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 91
 - ProcessMaker 4 v4.1.18

**Additional context**
Screenshot of error:
![image](https://user-images.githubusercontent.com/38859696/127506310-6fe93316-552f-438c-bf23-39700e9cb8c7.png)

Again, ideally the watcher settings would be updated to allow more than one output variable:
![image](https://user-images.githubusercontent.com/38859696/127505876-c6d9db1b-2605-417b-8333-57152fdba1ca.png)
Similar to the Data connector watcher:
![image](https://user-images.githubusercontent.com/38859696/127506064-0e8ceb3c-1555-4964-ab89-70732d332742.png)

**Comment by velkymx** [comment]
I appears your return in the script editor is not correct.

**Comment by velkymx** [comment]
Python is not a supported feature in this version. Please report issues to the correct support person.
