### ISSUE TITLE
 Class 'Laravel\Dusk\DuskServiceProvider' not found ... in fresh installation!!!

### ISSUE THREAD

**Issue by naamaan** [ProcessMaker/processmaker#3948]
**Describe the bug**
While installing I've got the following error:

_In Application.php line 679:

  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'Laravel\Dusk\DuskServiceProvider' not found

Exception trace:
  at /var/www/html/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:679
 Illuminate\Foundation\Application->resolveProvider() at /var/www/html/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:613
 Illuminate\Foundation\Application->register() at /var/www/html/processmaker/ProcessMaker/Providers/ProcessMakerServiceProvider.php:75
 ProcessMaker\Providers\ProcessMakerServiceProvider->register() at /var/www/html/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:616
 Illuminate\Foundation\Application->register() at /var/www/html/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:75
 Illuminate\Foundation\ProviderRepository->load() at /var/www/html/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:593
 Illuminate\Foundation\Application->registerConfiguredProviders() at /var/www/html/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php:17
 Illuminate\Foundation\Bootstrap\RegisterProviders->bootstrap() at /var/www/html/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:219
 Illuminate\Foundation\Application->bootstrapWith() at /var/www/html/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:320
 Illuminate\Foundation\Console\Kernel->bootstrap() at /var/www/html/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:129
 Illuminate\Foundation\Console\Kernel->handle() at /var/www/html/processmaker/artisan:31

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1_

**To Reproduce**
Follow the installation steps in the page
In the command: composer install --no-dev

**Desktop (please complete the following information):**
 - OS: Debian 10

**Comment by velkymx** [comment]
I guess your .env file has local or testing environment change it to production and it should be fine
composer install --no-dev --optimize-autoloader

This command is run for production.

Thanks

**Comment by naamaan** [comment]
Hi,
I'm new to Laravel applications, please forgive my ignorance, but I don't have .env file in the installation!!

I have:` .env.example` file in the directory, I did rename it to `.env` and the command worked.
Now executing the next command: `php artisan processmaker:install` tells the following:

_A .env file already exists. Stop the installation procedure, delete the existing .env file, and then restart the installation.
Remove the .env file to perform a new installation._

Should I accept this as OK for this step?

Thanks for your patience

**Comment by velkymx** [comment]
if you are running the installer you should remove the .env entirely

**Comment by naamaan** [comment]
If I removed the .env I'll ran into the original problem, the Dusk one !!!

**Comment by velkymx** [comment]
Hmm try https://laracasts.com/discuss/channels/laravel/class-laravelduskduskserviceprovider-not-found

**Comment by naamaan** [comment]
Hi,
Sorry for not being active for while, 

The bad news, is that I tried all the solutions above but still getting the error.

The good news, is the only thing that worked for me is to run: `composer install` instead of `composer install --no-dev`

Now I have the server up and running put facing problem with the _echo server port 6001_ as I think:

![image](https://user-images.githubusercontent.com/2176593/137638443-4f52775e-835d-4caf-8c42-00548de103b4.png)

I have two questions please:
1. Is my guessing about the error (6001 Port) wright?
2. Is it okay to run the server in dev mode like this?

Thanks for your patience,

Best regards,
