### ISSUE TITLE
processmaker4-v4.2.10.tar.gz is missing

### ISSUE THREAD

**Issue by dgomezleon** [ProcessMaker/processmaker#4001]
**Describe the bug** 
We use file processmaker4-v4.X.X.tar.gz as the source tarball for publishing processmaker solutions. However, this asset is not available. Could you please let us know if it is expected or if you plan to upload it?

Thanks in advance

**To Reproduce**
Look for processmaker4-v4.2.10.tar.gz asset in https://github.com/ProcessMaker/processmaker/releases/tag/v4.2.10

**Expected behavior**
Have processmaker4-v4.2.10.tar.gz available.

**Additional context**
We are Bitnami engineers that want to release new processmaker versions as soon as they are available in all the clouds we support.

**Comment by velkymx** [comment]
4.2.10 is an internal release. No tar provided
