### ISSUE TITLE
i get error when i start local server

### ISSUE THREAD

**Issue by sadat2002** [ProcessMaker/processmaker#4051]
hi,
when i start server on my localhost i get the belw error:

implode(): Passing glue string after array is deprecated. Swap the parameters

![image](https://user-images.githubusercontent.com/87799381/135714736-ecc2c8fe-fae7-4fcf-b6ba-976ecfa67dbe.png)

my php version is 7.4.3
my procssmaker version is the latest

**Comment by velkymx** [comment]
I'm sorry you're experiencing this problem. This issue is not present in the ProcessMaker 4 codebase.

**Comment by sadat2002** [comment]
> I'm sorry you're experiencing this problem. This issue is not present in the ProcessMaker 4 codebase.

but i use ProcessMaker 4.
