### ISSUE TITLE
Add build number to about page

### ISSUE THREAD

**Issue by ryancooley** [ProcessMaker/processmaker#4161]
**Is your feature request related to a problem? Please describe.**
As a developer I'd like to know the exact commit a version of ProcessMaker is running on.

**Describe the solution you'd like**
Add a build number underneath the copyright notice. Use the `<small>` tag to make the text smaller.

<img width="749" alt="Screen Shot 2021-11-18 at 11 19 22 AM" src="https://user-images.githubusercontent.com/867714/142482505-391423e9-3249-4fd6-bbcc-7840b1bef35a.png">

**Comment by runyan-co** [comment]
Ready for review @ryancooley.
