### ISSUE TITLE
WF 2.0 actions by email example

### ISSUE THREAD

**Issue by mdboyter** [ProcessMaker/processmaker#4371]
**Describe the bug**
using action by Email to send email with button included

**To Reproduce**
included in a model and run request

**Expected behavior**
expect an email

**Screenshots**
[Fatal error.docx](https://github.com/ProcessMaker/processmaker/files/8642531/Fatal.error.docx)

**Additional context**
get Fatal error: Uncaught GuzzleHttp\Exception\ServerException: Server error: `POST https://cu117-workflow2-test.elluciancloud.com/actions-by-email/send` resulted in a `500 Internal Server Error` response:

**Comment by PMQABen** [comment]
Based on your url, you seem to be using the Ellucian Workflow platform, which is powered by ProcessMaker. If you are a current Ellucian customer, we recommend sending your inquiry directly to [Ellucian Support](https://www.ellucian.com/customer-center). They may have additional resources, training materials to address your concern/request.
