### ISSUE TITLE
Cannot login - Login redirecting to login page

### ISSUE THREAD

**Issue by ameed-aabidi** [ProcessMaker/processmaker#4374]
**Describe the bug**
After installation of ProcessMaker 4 v4.2.29 in my Mac (which was an operation of its own), I was able to get ProcessMaker up on running with login screen. Though, before the login could appear, I had an issue with cache tagging (not sure if this is related directly with the actually) where it said cache tagging is not allowed with the type of cache storage I had. And with a little bit of research, I solved it by changing the adding `CACHE_DRIVER=array` in the `.env` file. However, after the login page loads, and I enter my credentials, it's redirecting me first to the 'request' page, which apparently is redirecting me to the 'login' page once again.
I know that my credentials are correct firstly because in my users table of the database, it clearly updates my last login column and also that when I check my requests/responses of the browser, after I click login, it's going through to the requests page. But the requests page is then giving me a 302 redirect back to my login page.
Need some help figuring out the culprit. Thanks in advance.

**To Reproduce**
1. Freshly installed ProcessMaker in MacOS (with AMP stack and NodeJS from Homebrew and Docker from the official docker website)
2. Enter valid and correct credentials to login in the login page.
3. Clicked on login. Ultimately redirected to the login page again.

**Expected behavior**
Login to the ProcessMaker application and be redirected the requests page.

**Screenshots**
Not applicable. Would share if deemed necessary.

**Desktop (please complete the following information):**
 - OS: MacOS 12.3.1 (M1)
 - Browser: Firefox
 - Version: 100.0

**Smartphone (please complete the following information):**
No smartphone used.

**Additional context**

**Comment by marcosbc** [comment]
Hi all, we are also seeing the same issue.

We reproduced this issue by installing ProcessMaker. Note that the resulting config file does not include the required `CACHE_DRIVER` config line as mentioned above. In our case, we used `CACHE_DRIVER=redis`. After configuring it, we tried to login but the result was the same: We get redirected back to the login page.

This is a sample `.env` configuration file that was generated with the setup script (with slight modifications such as the ones mentioned previously in this thread) and that we used to reproduce this issue:

```
APP_DEBUG=FALSE
APP_NAME="ProcessMaker"
APP_ENV=production
APP_KEY=base64:roVDp0Hndc26Kx8nOMhH3JTRv2MfjnzVplMOaUyfuh0=
APP_URL=http://localhost
BROADCAST_DRIVER=redis
BROADCASTER_HOST=http://localhost
BROADCASTER_KEY=21a795019957dde6bcd96142e05d4b10
LARAVEL_ECHO_SERVER_AUTH_HOST=http://localhost
LARAVEL_ECHO_SERVER_PORT=6001
LARAVEL_ECHO_SERVER_DEBUG=FALSE
PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_CLUSTER=
PUSHER_TLS=FALSE
PUSHER_DEBUG=FALSE
APP_TIMEZONE=UTC
DATE_FORMAT="m/d/Y H:i"
MAIN_LOGO_PATH="/img/processmaker_logo.png"
ICON_PATH_PATH="/img/processmaker_icon.png"
LOGIN_LOGO_PATH="img/processmaker_login.png"
REDIS_CLIENT=predis
REDIS_PREFIX=
HORIZON_PREFIX=horizon:
API_TIMEOUT=5000
PROXIES=*
LOGOUT_OTHER_DEVICES=false
BROWSER_CACHE=false
SESSION_DOMAIN=http://localhost
REDIS_HOST=127.0.0.1
DB_HOSTNAME=127.0.0.1
DB_PORT=3306
DB_DATABASE=bitnami_processmaker
DB_USERNAME=bn_processmaker
DB_PASSWORD=37a1b7d71df3c8cb569345468b2a52e7837b1c698fe0177daf06d1cc29b60e95
DB_DRIVER=mysql
DATA_DB_DRIVER=mysql
DATA_DB_HOST=127.0.0.1
DATA_DB_PORT=3306
DATA_DB_DATABASE=bitnami_processmaker
DATA_DB_USERNAME=bn_processmaker
DATA_DB_PASSWORD=37a1b7d71df3c8cb569345468b2a52e7837b1c698fe0177daf06d1cc29b60e95
DATA_DB_ENGINE=InnoDB
TELESCOPE_ENABLED=FALSE
PROCESSMAKER_SCRIPTS_HOME=/opt/bitnami/processmaker/storage/app/scripts
DOCKER_HOST_URL=http://localhost
HOME=/opt/bitnami/processmaker
PROCESSMAKER_SCRIPTS_DOCKER=/usr/bin/docker
CACHE_DRIVER=redis
SESSION_SECURE_COOKIE=true
REDIS_PORT=6379
```

> Note: We have tried to configure options such as `APP_URL`, `SESSION_DOMAIN` or `SESSION_SECURE_COOKIE`, with no results. In addition, enabling `APP_DEBUG` seems to have no effect on the log files.

**Comment by chau-huu** [comment]
Hi
See  the issue #3884

It works for me 

 "There is an option in config/session.php (around line 178) that I changed and solve my problem:
...
'secure' => env('SESSION_SECURE_COOKIE', true),
...
I put secure to false and now I can login"

**Comment by ameed-aabidi** [comment]
> 

Thanks. This worked out for me as well. I actually avoided playing around with the config/session.php and principally added a line in the .env file:
SESSION_SECURE_COOKIE=false

Worked like a charm.
