### ISSUE TITLE
Add hijri and jalali calendar and RTL language 

### ISSUE THREAD

**Issue by jntdst** [ProcessMaker/processmaker#4383]
Hello
I wanted to know if Process Maker 4, like version 3, supports RTL languages (right to left) such as Arabic and Persian or not?
  RTL language is the arrangement of items and language from right to left.
   Also, is it possible to change the calendar from the Gregorian calendar to hijri and jalali calendar?
If these are not supported, please include them in your future work.

example:
https://forum.processmaker.com/viewtopic.php?t=712953
https://stackoverflow.com/questions/27141627/change-date-process-maker-to-persian-date-jalali-or-add-date-picker-jalali

thanks

**Comment by PMQABen** [comment]
Thank you for your suggestions, I have passed it along to the ProcessMaker 4 product team.
