### ISSUE TITLE
npm install not working node version 16.18

### ISSUE THREAD

**Issue by aymankoo** [ProcessMaker/processmaker#4782]
npm install
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: @processmaker/processmaker@4.6.0
npm ERR! notsup Not compatible with your version of node/npm: @processmaker/processmaker@4.6.0
npm ERR! notsup Required: {"npm":"~8.19","node":"~16.18"}
npm ERR! notsup Actual:   {"npm":"9.6.6","node":"v18.16.0"}

**Comment by Manojait** [comment]
@aymankoo Pls change to decrease the npm and node version.
Steps:
**node:** 
- [Click here](https://nodejs.org/dist/v16.18.0/node-v16.18.0-x64.msi) the link and download the 16.18.0 node version
**npm:**
After installing the node version. Run this command --> npm install -gnpm@8.19.0

**Comment by Manojait** [comment]
Able to run the npm install comment, But I have faced another issue while running the npm install comment.

D:\processmaker-4.5.1\processmaker-4.5.1>npm install

> @processmaker/processmaker@4.5.1 postinstall
> mkdir -p public/css/precompiled && cp -rf node_modules/npm-font-open-sans public/css/precompiled/npm-font-open-sans && cp -rf node_modules/bootstrap/scss public/css/precompiled/bootstrap && cp -rf node_modules/@fortawesome/fontawesome-free public/css/precompiled/fontawesome-free && cp -rf node_modules/@processmaker/vue-multiselect/dist/vue-multiselect.min.css public/css/precompiled

The syntax of the command is incorrect.
npm ERR! code 1
npm ERR! path D:\processmaker-4.5.1\processmaker-4.5.1
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c mkdir -p public/css/precompiled && cp -rf node_modules/npm-font-open-sans public/css/precompiled/npm-font-open-sans && cp -rf node_modules/bootstrap/scss public/css/precompiled/bootstrap && cp -rf node_modules/@fortawesome/fontawesome-free public/css/precompiled/fontawesome-free && cp -rf node_modules/@processmaker/vue-multiselect/dist/vue-multiselect.min.css public/css/precompiled
