### ISSUE TITLE
MySql database connection issue

### ISSUE THREAD

**Issue by Manojait** [ProcessMaker/processmaker#4806]
While running the "PHP artisan processmaker:install" command, It throws a "Failed to connect MySQL database" error message. I have tried to install the processmaker using Vagrant. Attached the reference image.

![image](https://github.com/ProcessMaker/processmaker/assets/106147949/9336897b-7e35-4b66-8ecb-e3380e5f35f4)

**Comment by alirezaImani-f4L3e** [comment]
create `processmaker` database manually and try again .

**Comment by Manojait** [comment]
Hi @alirezaImani-f4L3e , Thanks for the reply.
I have created the processmaker database manually but still facing the same issue. Attached the image for reference. Could you please help us to resolve this issue?
Thanks...

![image](https://github.com/ProcessMaker/processmaker/assets/106147949/4d2a7a9e-d4d5-4bc4-9cd6-53236a2326ae)

When I try to connect the database manually, I can able t o login.
![image](https://github.com/ProcessMaker/processmaker/assets/106147949/13008f76-0a9b-4b18-bb2e-ae23970432eb)

**Comment by Manojait** [comment]
@alirezaImani-f4L3e , This issue has been fixed.

Steps:
1. Navigate to /etc/php/8.2/cli$ this file path in vagrant
2. Open the php.ini file 
3. Enable this "extension=pdo_mysql" extension.
4. Save the file and Restart the vagrant.
