### ISSUE TITLE
User List Dusk Test

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/processmaker#968]
- [ ] Use the user factory to generate 100 users

``factory(ProcessMaker\Models\User::class, 100)->create()``

- [ ] Visit /admin/users
- [ ] Verify we see "1 - 10 of 101 Users" on the page

Click on the navigation for page 2 

- [x] Verify we see "11 - 20 of 101 Users" on the page
- [x] Verify we see next / previous button

**Comment by velkymx** [comment]
@PMQABen can you take a pass at this please

**Comment by tdondich** [comment]
Laravel dusk should be installed as a DEV requirement.  When creating a production build, it's important to utilize --no-dev as the composer install.  Please see note: https://github.com/laravel/dusk/issues/289

@Cievoloth please be aware of this in the package building.

**Comment by Cievoloth** [comment]
@tdondich  Noted! 
Thanks!

**Comment by PMQABen** [comment]
This is the Dusk code I have so far. I can't do a proper test just yet with the 101 users, but I was able to force pagination by creating 11 users, and can extrapolate the commands from there:
```$this->browse(function ($browser) {
    $browser->visit("https://bpm4.local.processmaker.com/admin/users")
            ->type("#username","admin")
            ->type("#password","admin")
            ->click(".btn-success")
            ->assertMissing(".invalid-feedback")
    $browser->assertSeeIn("#users-listing", "1 - 10 of 101 Users")
            ->click(".fa-angle-right")
            ->pause(750)
            ->assertSeeIn("#users-listing", "11 - 20 of 101 Users")
            ->assertVisible(".fa-angle-left")
            ->assertVisible(".fa-angle-right");
```

Once Laravel Dusk is working correctly to setup the test environment, I can verify this.

**Comment by PMQABen** [comment]
Still unable to get the `factory()` thing to work, but if I end up manually creating 100 new users, then the Dusk code I pasted above works as intended.

**Comment by velkymx** [comment]
@PMQABen is it in a branch I can check out?

**Comment by PMQABen** [comment]
Have a look at https://github.com/ProcessMaker/bpm/tree/968-UserListDuskTest
